import type {
  Borrower,
  LOAApplication,
  Property,
} from "@/context/ApplicationContext";

function uid(seed: string): string {
  return `seed_${seed}`;
}

function dt(y: number, m: number, d: number): string {
  return new Date(y, m - 1, d).toISOString();
}

function dateStr(y: number, m: number, d: number): string {
  return `${String(m).padStart(2, "0")}/${String(d).padStart(2, "0")}/${y}`;
}

// ─── Borrowers ────────────────────────────────────────────────────────────────

export const SEED_BORROWERS: Borrower[] = [
  {
    id: uid("b01"), createdAt: dt(2026, 1, 5), updatedAt: dt(2026, 2, 10),
    firstName: "James", lastName: "Hartley", entityName: "Hartley Capital Partners LLC",
    email: "j.hartley@hartleycap.com", phone: "(212) 555-0181",
    creExperienceYears: "18", netWorthUsd: "24,500,000", liquidityUsd: "4,200,000",
    creditScore: "748",
  },
  {
    id: uid("b02"), createdAt: dt(2026, 1, 12), updatedAt: dt(2026, 2, 15),
    firstName: "Maria", lastName: "Santos", entityName: "Santos Real Estate Group Inc",
    email: "msantos@sreg.com", phone: "(213) 555-0247",
    creExperienceYears: "14", netWorthUsd: "18,000,000", liquidityUsd: "2,800,000",
    creditScore: "761",
  },
  {
    id: uid("b03"), createdAt: dt(2026, 1, 20), updatedAt: dt(2026, 3, 1),
    firstName: "David", lastName: "Chen", entityName: "Chen Properties LLC",
    email: "dchen@chenproperties.com", phone: "(415) 555-0312",
    creExperienceYears: "22", netWorthUsd: "41,000,000", liquidityUsd: "7,500,000",
    creditScore: "782",
  },
  {
    id: uid("b04"), createdAt: dt(2026, 2, 3), updatedAt: dt(2026, 3, 8),
    firstName: "Rachel", lastName: "Kim", entityName: "Meridian Investments Group",
    email: "rkim@meridian-inv.com", phone: "(312) 555-0499",
    creExperienceYears: "11", netWorthUsd: "12,750,000", liquidityUsd: "1,900,000",
    creditScore: "733",
  },
  {
    id: uid("b05"), createdAt: dt(2026, 2, 10), updatedAt: dt(2026, 3, 5),
    firstName: "Thomas", lastName: "Brooks", entityName: "Brooks & Associates CRE",
    email: "tbrooks@brooksassoc.com", phone: "(713) 555-0560",
    creExperienceYears: "9", netWorthUsd: "8,200,000", liquidityUsd: "1,100,000",
    creditScore: "719",
  },
  {
    id: uid("b06"), createdAt: dt(2026, 2, 18), updatedAt: dt(2026, 3, 12),
    firstName: "Sarah", lastName: "Mitchell", entityName: "Mitchell Commercial Real Estate LLC",
    email: "smitchell@mitchellcre.com", phone: "(305) 555-0623",
    creExperienceYears: "16", netWorthUsd: "31,000,000", liquidityUsd: "5,400,000",
    creditScore: "769",
  },
  {
    id: uid("b07"), createdAt: dt(2026, 1, 28), updatedAt: dt(2026, 3, 15),
    firstName: "Robert", lastName: "Nguyen", entityName: "Pacific Coast Holdings Corp",
    email: "rnguyen@paccoasthold.com", phone: "(949) 555-0778",
    creExperienceYears: "20", netWorthUsd: "55,000,000", liquidityUsd: "9,100,000",
    creditScore: "795",
  },
  {
    id: uid("b08"), createdAt: dt(2026, 3, 2), updatedAt: dt(2026, 3, 20),
    firstName: "Evelyn", lastName: "Carter", entityName: "Carter Development Corporation",
    email: "ecarter@carterdevelopment.com", phone: "(512) 555-0834",
    creExperienceYears: "7", netWorthUsd: "6,500,000", liquidityUsd: "900,000",
    creditScore: "",  // Not yet at Application Start — ECOA compliant
  },
];

// ─── Properties ───────────────────────────────────────────────────────────────

export const SEED_PROPERTIES: Property[] = [
  {
    id: uid("p01"), createdAt: dt(2026, 1, 5), updatedAt: dt(2026, 2, 10),
    streetAddress: "1200 Market Street", city: "Philadelphia", state: "PA", zipCode: "19107",
    propertyType: "Office", grossSqFt: "124,000", numberOfUnits: "", yearBuilt: "2004",
    physicalOccupancyPct: "88", economicOccupancyPct: "85",
  },
  {
    id: uid("p02"), createdAt: dt(2026, 1, 12), updatedAt: dt(2026, 2, 15),
    streetAddress: "850 Fifth Avenue", city: "New York", state: "NY", zipCode: "10065",
    propertyType: "Retail", grossSqFt: "36,500", numberOfUnits: "12", yearBuilt: "1998",
    physicalOccupancyPct: "92", economicOccupancyPct: "89",
  },
  {
    id: uid("p03"), createdAt: dt(2026, 1, 20), updatedAt: dt(2026, 3, 1),
    streetAddress: "4400 Industrial Boulevard", city: "Atlanta", state: "GA", zipCode: "30336",
    propertyType: "Industrial", grossSqFt: "312,000", numberOfUnits: "", yearBuilt: "2011",
    physicalOccupancyPct: "95", economicOccupancyPct: "94",
  },
  {
    id: uid("p04"), createdAt: dt(2026, 2, 3), updatedAt: dt(2026, 3, 8),
    streetAddress: "2800 Wilshire Boulevard", city: "Los Angeles", state: "CA", zipCode: "90057",
    propertyType: "Multifamily", grossSqFt: "98,400", numberOfUnits: "120", yearBuilt: "2016",
    physicalOccupancyPct: "96", economicOccupancyPct: "93",
  },
  {
    id: uid("p05"), createdAt: dt(2026, 2, 10), updatedAt: dt(2026, 3, 5),
    streetAddress: "330 North Michigan Avenue", city: "Chicago", state: "IL", zipCode: "60601",
    propertyType: "Mixed Use", grossSqFt: "78,200", numberOfUnits: "48", yearBuilt: "2008",
    physicalOccupancyPct: "91", economicOccupancyPct: "88",
  },
  {
    id: uid("p06"), createdAt: dt(2026, 2, 18), updatedAt: dt(2026, 3, 12),
    streetAddress: "600 Congress Avenue", city: "Austin", state: "TX", zipCode: "78701",
    propertyType: "Office", grossSqFt: "55,000", numberOfUnits: "", yearBuilt: "2019",
    physicalOccupancyPct: "82", economicOccupancyPct: "80",
  },
  {
    id: uid("p07"), createdAt: dt(2026, 1, 28), updatedAt: dt(2026, 3, 15),
    streetAddress: "1500 Brickell Avenue", city: "Miami", state: "FL", zipCode: "33131",
    propertyType: "Hotel", grossSqFt: "145,000", numberOfUnits: "218", yearBuilt: "2014",
    physicalOccupancyPct: "79", economicOccupancyPct: "74",
  },
  {
    id: uid("p08"), createdAt: dt(2026, 2, 5), updatedAt: dt(2026, 3, 10),
    streetAddress: "3200 Peachtree Road NE", city: "Atlanta", state: "GA", zipCode: "30305",
    propertyType: "Multifamily", grossSqFt: "182,000", numberOfUnits: "224", yearBuilt: "2018",
    physicalOccupancyPct: "97", economicOccupancyPct: "95",
  },
  {
    id: uid("p09"), createdAt: dt(2026, 2, 22), updatedAt: dt(2026, 3, 18),
    streetAddress: "900 North Michigan Avenue", city: "Chicago", state: "IL", zipCode: "60611",
    propertyType: "Retail", grossSqFt: "44,600", numberOfUnits: "8", yearBuilt: "2001",
    physicalOccupancyPct: "100", economicOccupancyPct: "97",
  },
  {
    id: uid("p10"), createdAt: dt(2026, 1, 15), updatedAt: dt(2026, 3, 20),
    streetAddress: "555 California Street", city: "San Francisco", state: "CA", zipCode: "94104",
    propertyType: "Office", grossSqFt: "208,000", numberOfUnits: "", yearBuilt: "2007",
    physicalOccupancyPct: "86", economicOccupancyPct: "83",
  },
  {
    id: uid("p11"), createdAt: dt(2026, 3, 1), updatedAt: dt(2026, 3, 18),
    streetAddress: "7800 Airport Boulevard", city: "Houston", state: "TX", zipCode: "77061",
    propertyType: "Industrial", grossSqFt: "425,000", numberOfUnits: "", yearBuilt: "2015",
    physicalOccupancyPct: "100", economicOccupancyPct: "100",
  },
  {
    id: uid("p12"), createdAt: dt(2026, 3, 8), updatedAt: dt(2026, 3, 20),
    streetAddress: "2100 East Camelback Road", city: "Phoenix", state: "AZ", zipCode: "85016",
    propertyType: "Self Storage", grossSqFt: "62,000", numberOfUnits: "480", yearBuilt: "2020",
    physicalOccupancyPct: "88", economicOccupancyPct: "86",
  },
];

// ─── Applications ─────────────────────────────────────────────────────────────

export const SEED_APPLICATIONS: LOAApplication[] = [
  // ── 1. Inquiry — Office Philadelphia ─────────────────────────────────────────
  {
    id: uid("a01"), createdAt: dt(2026, 3, 14), updatedAt: dt(2026, 3, 14),
    status: "Inquiry",
    borrowerId: uid("b08"), propertyId: uid("p01"),
    loanType: "Acquisition", loanAmountUsd: "8,500,000", loanTermYears: "10",
    interestType: "Fixed", interestRatePct: "6.75", amortizationType: "Full Amortizing",
    ltvPct: "65", dscrRatio: "1.28", targetClosingDate: dateStr(2026, 7, 15),
    inquiryNotes: "Borrower is exploring acquisition of stabilized office building in Center City. Has toured the property twice. Asking price $13M. Looking for 65% LTV conventional financing. Market is recovering post-COVID — occupancy trending up from 82% to 88%.",
    creditBoxNotes: "", loiRecommended: false, loiIssuedDate: "", loiExpirationDate: "",
    applicationDepositAmountUsd: "", applicationDepositDate: "", signedLoiDate: "",
    debitAuthorizationDate: "", rateLockEnabled: false, rateLockRatePct: "", rateLockExpirationDate: "",
    appraisalOrderedDate: "", appraisalCompletedDate: "", appraisalValueUsd: "",
    environmentalStatus: "", borrowerFormsStatus: "",
    commitmentLetterRecommended: false, commitmentLetterIssuedDate: "",
    conditionalApprovals: "", creditRiskExceptions: "",
    hmdaComplete: false, hmdaNotes: "",
    insuranceCarrier: "", insurancePolicyNumber: "", insuranceEffectiveDate: "",
    titleCompany: "", escrowCompany: "", floodZoneDesignation: "", titleReportDate: "",
    docsDrawnDate: "", settlementFeesUsd: "", settlementStatementDate: "",
    docsBackDate: "", titleConfirmationDate: "",
    wireAmountUsd: "", wireBankName: "", wireAbaNumber: "", wireAccountNumber: "",
    servicingLoanNumber: "", bookingDate: "",
    comments: [
      { id: uid("c01a"), applicationId: uid("a01"), parentCommentId: null, author: "Jennifer Walsh (Sales)", text: "Initial call with borrower went well. Strong equity position and long track record in Philly office market.", createdAt: dt(2026, 3, 14) },
    ],
    attachments: [],
  },

  // ── 2. Letter of Interest — Retail New York ──────────────────────────────────
  {
    id: uid("a02"), createdAt: dt(2026, 2, 20), updatedAt: dt(2026, 3, 5),
    status: "Letter of Interest",
    borrowerId: uid("b04"), propertyId: uid("p02"),
    loanType: "Refinance", loanAmountUsd: "12,200,000", loanTermYears: "7",
    interestType: "Fixed", interestRatePct: "6.40", amortizationType: "Interest Only",
    ltvPct: "60", dscrRatio: "1.45", targetClosingDate: dateStr(2026, 6, 30),
    inquiryNotes: "Borrower seeking cash-out refinance on flagship retail property in Midtown. Current loan maturity in August. Strong anchor tenant (national pharmacy chain) with 9 years remaining on NNN lease.",
    creditBoxNotes: "Deal fits credit box well. Cap rate of 5.2% aligns with market. Anchor tenant NNN lease provides strong debt service coverage. IO period justified given lease term remaining. Recommend LOI.",
    loiRecommended: true, loiIssuedDate: dateStr(2026, 3, 5), loiExpirationDate: dateStr(2026, 4, 5),
    applicationDepositAmountUsd: "", applicationDepositDate: "", signedLoiDate: "",
    debitAuthorizationDate: "", rateLockEnabled: false, rateLockRatePct: "", rateLockExpirationDate: "",
    appraisalOrderedDate: "", appraisalCompletedDate: "", appraisalValueUsd: "",
    environmentalStatus: "", borrowerFormsStatus: "",
    commitmentLetterRecommended: false, commitmentLetterIssuedDate: "",
    conditionalApprovals: "", creditRiskExceptions: "",
    hmdaComplete: false, hmdaNotes: "",
    insuranceCarrier: "", insurancePolicyNumber: "", insuranceEffectiveDate: "",
    titleCompany: "", escrowCompany: "", floodZoneDesignation: "", titleReportDate: "",
    docsDrawnDate: "", settlementFeesUsd: "", settlementStatementDate: "",
    docsBackDate: "", titleConfirmationDate: "",
    wireAmountUsd: "", wireBankName: "", wireAbaNumber: "", wireAccountNumber: "",
    servicingLoanNumber: "", bookingDate: "",
    comments: [
      { id: uid("c02a"), applicationId: uid("a02"), parentCommentId: null, author: "Alan Morse (Credit Risk)", text: "LOI issued 3/5. Waiting on borrower to review terms and execute.", createdAt: dt(2026, 3, 5) },
      { id: uid("c02b"), applicationId: uid("a02"), parentCommentId: uid("c02a"), author: "Jennifer Walsh (Sales)", text: "Borrower confirmed receipt. Expects to sign by 3/12.", createdAt: dt(2026, 3, 6) },
    ],
    attachments: [],
  },

  // ── 3. Application Start — Industrial Atlanta ────────────────────────────────
  {
    id: uid("a03"), createdAt: dt(2026, 2, 5), updatedAt: dt(2026, 3, 10),
    status: "Application Start",
    borrowerId: uid("b01"), propertyId: uid("p03"),
    loanType: "Acquisition", loanAmountUsd: "19,500,000", loanTermYears: "10",
    interestType: "Fixed", interestRatePct: "6.20", amortizationType: "Full Amortizing",
    ltvPct: "62", dscrRatio: "1.52", targetClosingDate: dateStr(2026, 5, 30),
    inquiryNotes: "Class A industrial acquisition near Hartsfield-Jackson. Two NNN tenants — logistics company and e-commerce fulfillment. Excellent location fundamentals.",
    creditBoxNotes: "Strong industrial fundamentals. 95% physical occupancy with long-term tenants. Fits core credit box. DSCR well above 1.35x floor. Recommend LOI.",
    loiRecommended: true, loiIssuedDate: dateStr(2026, 2, 15), loiExpirationDate: dateStr(2026, 3, 15),
    applicationDepositAmountUsd: "25,000", applicationDepositDate: dateStr(2026, 3, 8),
    signedLoiDate: dateStr(2026, 3, 2), debitAuthorizationDate: dateStr(2026, 3, 8),
    rateLockEnabled: false, rateLockRatePct: "", rateLockExpirationDate: "",
    appraisalOrderedDate: "", appraisalCompletedDate: "", appraisalValueUsd: "",
    environmentalStatus: "", borrowerFormsStatus: "Not Started",
    commitmentLetterRecommended: false, commitmentLetterIssuedDate: "",
    conditionalApprovals: "", creditRiskExceptions: "",
    hmdaComplete: false, hmdaNotes: "",
    insuranceCarrier: "", insurancePolicyNumber: "", insuranceEffectiveDate: "",
    titleCompany: "", escrowCompany: "", floodZoneDesignation: "", titleReportDate: "",
    docsDrawnDate: "", settlementFeesUsd: "", settlementStatementDate: "",
    docsBackDate: "", titleConfirmationDate: "",
    wireAmountUsd: "", wireBankName: "", wireAbaNumber: "", wireAccountNumber: "",
    servicingLoanNumber: "", bookingDate: "",
    comments: [
      { id: uid("c03a"), applicationId: uid("a03"), parentCommentId: null, author: "Jennifer Walsh (Sales)", text: "Deposit received 3/8. Debit auth also signed. Kicking off application package.", createdAt: dt(2026, 3, 10) },
    ],
    attachments: [],
  },

  // ── 4. Application Processing — Multifamily LA ───────────────────────────────
  {
    id: uid("a04"), createdAt: dt(2026, 1, 15), updatedAt: dt(2026, 3, 18),
    status: "Application Processing",
    borrowerId: uid("b02"), propertyId: uid("p04"),
    loanType: "Refinance", loanAmountUsd: "22,400,000", loanTermYears: "10",
    interestType: "Fixed", interestRatePct: "6.00", amortizationType: "Full Amortizing",
    ltvPct: "58", dscrRatio: "1.60", targetClosingDate: dateStr(2026, 5, 15),
    inquiryNotes: "Multifamily refinance of 120-unit complex in Koreatown. Current loan at 5.5% maturing in June. Borrower wants to lock in current rate before further market movement.",
    creditBoxNotes: "96% occupancy well above 90% hurdle. DSCR of 1.60x provides strong cushion. LA multifamily fundamentals remain robust. Recommend LOI.",
    loiRecommended: true, loiIssuedDate: dateStr(2026, 2, 1), loiExpirationDate: dateStr(2026, 3, 1),
    applicationDepositAmountUsd: "30,000", applicationDepositDate: dateStr(2026, 2, 20),
    signedLoiDate: dateStr(2026, 2, 15), debitAuthorizationDate: dateStr(2026, 2, 20),
    rateLockEnabled: false, rateLockRatePct: "", rateLockExpirationDate: "",
    appraisalOrderedDate: dateStr(2026, 3, 1), appraisalCompletedDate: "",
    appraisalValueUsd: "", environmentalStatus: "In Progress", borrowerFormsStatus: "Packaged",
    commitmentLetterRecommended: false, commitmentLetterIssuedDate: "",
    conditionalApprovals: "", creditRiskExceptions: "",
    hmdaComplete: false, hmdaNotes: "",
    insuranceCarrier: "", insurancePolicyNumber: "", insuranceEffectiveDate: "",
    titleCompany: "", escrowCompany: "", floodZoneDesignation: "", titleReportDate: "",
    docsDrawnDate: "", settlementFeesUsd: "", settlementStatementDate: "",
    docsBackDate: "", titleConfirmationDate: "",
    wireAmountUsd: "", wireBankName: "", wireAbaNumber: "", wireAccountNumber: "",
    servicingLoanNumber: "", bookingDate: "",
    comments: [
      { id: uid("c04a"), applicationId: uid("a04"), parentCommentId: null, author: "Lisa Park (Processing)", text: "Appraisal ordered 3/1 with Pacific Valuation Group. Est. completion 3/28.", createdAt: dt(2026, 3, 1) },
      { id: uid("c04b"), applicationId: uid("a04"), parentCommentId: null, author: "Lisa Park (Processing)", text: "Phase I Environmental ordered. Awaiting site access confirmation.", createdAt: dt(2026, 3, 8) },
    ],
    attachments: [],
  },

  // ── 5. Final Credit Review — Mixed Use Chicago ───────────────────────────────
  {
    id: uid("a05"), createdAt: dt(2026, 1, 8), updatedAt: dt(2026, 3, 19),
    status: "Final Credit Review",
    borrowerId: uid("b07"), propertyId: uid("p05"),
    loanType: "Acquisition", loanAmountUsd: "15,750,000", loanTermYears: "10",
    interestType: "Floating", interestRatePct: "7.10", amortizationType: "Partial IO",
    ltvPct: "63", dscrRatio: "1.38", targetClosingDate: dateStr(2026, 4, 30),
    inquiryNotes: "Mixed-use asset in Streeterville. Ground floor retail (2 units) + 48 residential apartments above. Strong River North submarket fundamentals.",
    creditBoxNotes: "Mixed-use with residential majority qualifies under multifamily program. Floating rate with 3yr IO is appropriate for value-add business plan. Recommend LOI with conditions.",
    loiRecommended: true, loiIssuedDate: dateStr(2026, 1, 20), loiExpirationDate: dateStr(2026, 2, 20),
    applicationDepositAmountUsd: "20,000", applicationDepositDate: dateStr(2026, 2, 5),
    signedLoiDate: dateStr(2026, 2, 3), debitAuthorizationDate: dateStr(2026, 2, 5),
    rateLockEnabled: true, rateLockRatePct: "7.10", rateLockExpirationDate: dateStr(2026, 5, 15),
    appraisalOrderedDate: dateStr(2026, 2, 8), appraisalCompletedDate: dateStr(2026, 3, 5),
    appraisalValueUsd: "25,100,000", environmentalStatus: "Clear", borrowerFormsStatus: "Received",
    commitmentLetterRecommended: false, commitmentLetterIssuedDate: "",
    conditionalApprovals: "Borrower to maintain minimum DSCR of 1.25x on a trailing 12-month basis\nBorrower must maintain $500K liquidity reserve\nNo additional debt to be incurred without lender consent",
    creditRiskExceptions: "Floating rate exception approved by CRO: floating SOFR + 175bps justified by value-add business plan",
    hmdaComplete: false, hmdaNotes: "",
    insuranceCarrier: "", insurancePolicyNumber: "", insuranceEffectiveDate: "",
    titleCompany: "", escrowCompany: "", floodZoneDesignation: "", titleReportDate: "",
    docsDrawnDate: "", settlementFeesUsd: "", settlementStatementDate: "",
    docsBackDate: "", titleConfirmationDate: "",
    wireAmountUsd: "", wireBankName: "", wireAbaNumber: "", wireAccountNumber: "",
    servicingLoanNumber: "", bookingDate: "",
    comments: [
      { id: uid("c05a"), applicationId: uid("a05"), parentCommentId: null, author: "Alan Morse (Credit Risk)", text: "Credit memo drafted and under review with CRO. Appraisal came in at $25.1M — slightly above purchase price. Good news.", createdAt: dt(2026, 3, 18) },
      { id: uid("c05b"), applicationId: uid("a05"), parentCommentId: uid("c05a"), author: "Priya Nair (CRO)", text: "Reviewed. Floating rate exception approved. Proceeding to CL recommendation.", createdAt: dt(2026, 3, 19) },
    ],
    attachments: [],
  },

  // ── 6. Pre-close — Office Austin ─────────────────────────────────────────────
  {
    id: uid("a06"), createdAt: dt(2025, 12, 10), updatedAt: dt(2026, 3, 20),
    status: "Pre-close",
    borrowerId: uid("b06"), propertyId: uid("p06"),
    loanType: "Acquisition", loanAmountUsd: "9,800,000", loanTermYears: "10",
    interestType: "Fixed", interestRatePct: "6.55", amortizationType: "Full Amortizing",
    ltvPct: "65", dscrRatio: "1.41", targetClosingDate: dateStr(2026, 4, 15),
    inquiryNotes: "Tech-leased office building in downtown Austin. Single tenant NNN — 5 years remaining. Borrower has existing relationship with bank.",
    creditBoxNotes: "Single tenant risk noted but offset by strong covenant. DSCR above floor. Recommend LOI.",
    loiRecommended: true, loiIssuedDate: dateStr(2025, 12, 28), loiExpirationDate: dateStr(2026, 1, 28),
    applicationDepositAmountUsd: "15,000", applicationDepositDate: dateStr(2026, 1, 20),
    signedLoiDate: dateStr(2026, 1, 15), debitAuthorizationDate: dateStr(2026, 1, 20),
    rateLockEnabled: true, rateLockRatePct: "6.55", rateLockExpirationDate: dateStr(2026, 4, 30),
    appraisalOrderedDate: dateStr(2026, 1, 22), appraisalCompletedDate: dateStr(2026, 2, 18),
    appraisalValueUsd: "15,200,000", environmentalStatus: "Clear", borrowerFormsStatus: "Received",
    commitmentLetterRecommended: true, commitmentLetterIssuedDate: dateStr(2026, 3, 10),
    conditionalApprovals: "Borrower to provide final executed lease abstract\nBorrower insurance policy must be in effect at closing",
    creditRiskExceptions: "Single-tenant concentration exception: approved given NNN lease covenant and borrower net worth of $31M",
    hmdaComplete: false, hmdaNotes: "HMDA LAR fields 90% complete — still need census tract code and action taken date.",
    insuranceCarrier: "", insurancePolicyNumber: "", insuranceEffectiveDate: "",
    titleCompany: "", escrowCompany: "", floodZoneDesignation: "", titleReportDate: "",
    docsDrawnDate: "", settlementFeesUsd: "", settlementStatementDate: "",
    docsBackDate: "", titleConfirmationDate: "",
    wireAmountUsd: "", wireBankName: "", wireAbaNumber: "", wireAccountNumber: "",
    servicingLoanNumber: "", bookingDate: "",
    comments: [
      { id: uid("c06a"), applicationId: uid("a06"), parentCommentId: null, author: "Lisa Park (Processing)", text: "HMDA nearly complete — missing census tract. Requesting from GIS team.", createdAt: dt(2026, 3, 20) },
    ],
    attachments: [],
  },

  // ── 7. Ready for Docs — Hotel Miami ──────────────────────────────────────────
  {
    id: uid("a07"), createdAt: dt(2025, 11, 5), updatedAt: dt(2026, 3, 15),
    status: "Ready for Docs",
    borrowerId: uid("b07"), propertyId: uid("p07"),
    loanType: "Refinance", loanAmountUsd: "28,500,000", loanTermYears: "5",
    interestType: "Floating", interestRatePct: "7.45", amortizationType: "Interest Only",
    ltvPct: "55", dscrRatio: "1.32", targetClosingDate: dateStr(2026, 4, 10),
    inquiryNotes: "Boutique hotel refinance on Brickell Avenue. Post-renovation stabilization complete. Strong ADR and RevPAR metrics for the submarket.",
    creditBoxNotes: "Hotel sector exception required. Post-renovation performance data reviewed. Revenue trending above underwriting. IO approved for 5yr term.",
    loiRecommended: true, loiIssuedDate: dateStr(2025, 11, 25), loiExpirationDate: dateStr(2025, 12, 25),
    applicationDepositAmountUsd: "50,000", applicationDepositDate: dateStr(2025, 12, 18),
    signedLoiDate: dateStr(2025, 12, 15), debitAuthorizationDate: dateStr(2025, 12, 18),
    rateLockEnabled: true, rateLockRatePct: "7.45", rateLockExpirationDate: dateStr(2026, 4, 30),
    appraisalOrderedDate: dateStr(2026, 1, 5), appraisalCompletedDate: dateStr(2026, 2, 10),
    appraisalValueUsd: "52,000,000", environmentalStatus: "Clear", borrowerFormsStatus: "Received",
    commitmentLetterRecommended: true, commitmentLetterIssuedDate: dateStr(2026, 2, 28),
    conditionalApprovals: "Borrower to maintain DSCR ≥ 1.25x on trailing 12 months\nOperating account to be maintained at JP Morgan Chase\nPledge of equity interests in property-owning entity",
    creditRiskExceptions: "Hotel asset class exception: approved by Credit Committee 2/22/2026\nIO structure exception for hospitality: approved",
    hmdaComplete: true, hmdaNotes: "HMDA complete. All LAR fields verified 3/12.",
    insuranceCarrier: "Chubb Insurance Company", insurancePolicyNumber: "CHB-2026-0078341",
    insuranceEffectiveDate: dateStr(2026, 4, 10),
    titleCompany: "Chicago Title Insurance Company",
    escrowCompany: "First American Title",
    floodZoneDesignation: "Zone X",
    titleReportDate: dateStr(2026, 3, 10),
    docsDrawnDate: "", settlementFeesUsd: "", settlementStatementDate: "",
    docsBackDate: "", titleConfirmationDate: "",
    wireAmountUsd: "", wireBankName: "", wireAbaNumber: "", wireAccountNumber: "",
    servicingLoanNumber: "", bookingDate: "",
    comments: [
      { id: uid("c07a"), applicationId: uid("a07"), parentCommentId: null, author: "Marcus Hill (Closing)", text: "All third-party items confirmed. Title report clean. Ready to request docs.", createdAt: dt(2026, 3, 15) },
    ],
    attachments: [],
  },

  // ── 8. Docs Drawn — Multifamily Atlanta ──────────────────────────────────────
  {
    id: uid("a08"), createdAt: dt(2025, 10, 20), updatedAt: dt(2026, 3, 18),
    status: "Docs Drawn",
    borrowerId: uid("b03"), propertyId: uid("p08"),
    loanType: "Acquisition", loanAmountUsd: "32,100,000", loanTermYears: "10",
    interestType: "Fixed", interestRatePct: "5.95", amortizationType: "Full Amortizing",
    ltvPct: "60", dscrRatio: "1.58", targetClosingDate: dateStr(2026, 3, 28),
    inquiryNotes: "224-unit garden-style multifamily in Buckhead. Class A property, 2018 vintage. Seller has accepted offer at $53.5M.",
    creditBoxNotes: "Best-in-class Buckhead multifamily. 97% occupancy, strong rent growth trajectory. DSCR of 1.58x well above floor.",
    loiRecommended: true, loiIssuedDate: dateStr(2025, 11, 5), loiExpirationDate: dateStr(2025, 12, 5),
    applicationDepositAmountUsd: "50,000", applicationDepositDate: dateStr(2025, 11, 25),
    signedLoiDate: dateStr(2025, 11, 20), debitAuthorizationDate: dateStr(2025, 11, 25),
    rateLockEnabled: true, rateLockRatePct: "5.95", rateLockExpirationDate: dateStr(2026, 4, 15),
    appraisalOrderedDate: dateStr(2025, 12, 1), appraisalCompletedDate: dateStr(2026, 1, 12),
    appraisalValueUsd: "53,800,000", environmentalStatus: "Clear", borrowerFormsStatus: "Received",
    commitmentLetterRecommended: true, commitmentLetterIssuedDate: dateStr(2026, 2, 5),
    conditionalApprovals: "Borrower to provide executed purchase and sale agreement\nTitle search must confirm no recorded liens\nBorrower reserves of 3 months PITIA to be funded at closing",
    creditRiskExceptions: "",
    hmdaComplete: true, hmdaNotes: "HMDA LAR complete and validated 2/28.",
    insuranceCarrier: "Travelers Property Casualty", insurancePolicyNumber: "TRV-2026-0041829",
    insuranceEffectiveDate: dateStr(2026, 3, 28),
    titleCompany: "Fidelity National Title",
    escrowCompany: "Fidelity National Title",
    floodZoneDesignation: "Zone X",
    titleReportDate: dateStr(2026, 2, 20),
    docsDrawnDate: dateStr(2026, 3, 18), settlementFeesUsd: "48,500",
    settlementStatementDate: dateStr(2026, 3, 18),
    docsBackDate: "", titleConfirmationDate: "",
    wireAmountUsd: "", wireBankName: "", wireAbaNumber: "", wireAccountNumber: "",
    servicingLoanNumber: "", bookingDate: "",
    comments: [
      { id: uid("c08a"), applicationId: uid("a08"), parentCommentId: null, author: "Marcus Hill (Closing)", text: "Loan documents generated and sent to borrower's counsel. Expecting execution by 3/22.", createdAt: dt(2026, 3, 18) },
    ],
    attachments: [],
  },

  // ── 9. Docs Back — Retail Chicago ────────────────────────────────────────────
  {
    id: uid("a09"), createdAt: dt(2025, 10, 1), updatedAt: dt(2026, 3, 20),
    status: "Docs Back",
    borrowerId: uid("b04"), propertyId: uid("p09"),
    loanType: "Refinance", loanAmountUsd: "17,800,000", loanTermYears: "7",
    interestType: "Fixed", interestRatePct: "6.15", amortizationType: "Interest Only",
    ltvPct: "58", dscrRatio: "1.55", targetClosingDate: dateStr(2026, 3, 26),
    inquiryNotes: "Iconic Michigan Avenue retail — 100% occupied with mix of luxury and fashion tenants. National credit tenants on long-term leases.",
    creditBoxNotes: "Trophy retail asset on premier US shopping corridor. 100% occupancy, all national credit tenants. Very low risk profile.",
    loiRecommended: true, loiIssuedDate: dateStr(2025, 10, 20), loiExpirationDate: dateStr(2025, 11, 20),
    applicationDepositAmountUsd: "25,000", applicationDepositDate: dateStr(2025, 11, 10),
    signedLoiDate: dateStr(2025, 11, 5), debitAuthorizationDate: dateStr(2025, 11, 10),
    rateLockEnabled: true, rateLockRatePct: "6.15", rateLockExpirationDate: dateStr(2026, 4, 1),
    appraisalOrderedDate: dateStr(2025, 11, 12), appraisalCompletedDate: dateStr(2025, 12, 20),
    appraisalValueUsd: "30,800,000", environmentalStatus: "Clear", borrowerFormsStatus: "Received",
    commitmentLetterRecommended: true, commitmentLetterIssuedDate: dateStr(2026, 1, 15),
    conditionalApprovals: "Borrower to provide current rent roll executed by all tenants\nInsurance policy to name lender as additional insured and loss payee",
    creditRiskExceptions: "IO structure exception for retail: approved given national credit tenant profile",
    hmdaComplete: true, hmdaNotes: "Complete.",
    insuranceCarrier: "Liberty Mutual Insurance", insurancePolicyNumber: "LM-2026-0095214",
    insuranceEffectiveDate: dateStr(2026, 3, 26),
    titleCompany: "Chicago Title Insurance Company",
    escrowCompany: "Chicago Title Insurance Company",
    floodZoneDesignation: "Zone X",
    titleReportDate: dateStr(2026, 3, 1),
    docsDrawnDate: dateStr(2026, 3, 14), settlementFeesUsd: "32,500",
    settlementStatementDate: dateStr(2026, 3, 14),
    docsBackDate: dateStr(2026, 3, 20), titleConfirmationDate: dateStr(2026, 3, 20),
    wireAmountUsd: "", wireBankName: "", wireAbaNumber: "", wireAccountNumber: "",
    servicingLoanNumber: "", bookingDate: "",
    comments: [
      { id: uid("c09a"), applicationId: uid("a09"), parentCommentId: null, author: "Marcus Hill (Closing)", text: "Signed docs received from borrower's counsel 3/20. Title confirmed. Ready to wire.", createdAt: dt(2026, 3, 20) },
    ],
    attachments: [],
  },

  // ── 10. Closing — Office San Francisco ───────────────────────────────────────
  {
    id: uid("a10"), createdAt: dt(2025, 9, 15), updatedAt: dt(2026, 3, 21),
    status: "Closing",
    borrowerId: uid("b03"), propertyId: uid("p10"),
    loanType: "Refinance", loanAmountUsd: "41,600,000", loanTermYears: "10",
    interestType: "Fixed", interestRatePct: "5.85", amortizationType: "Full Amortizing",
    ltvPct: "55", dscrRatio: "1.62", targetClosingDate: dateStr(2026, 3, 24),
    inquiryNotes: "Class A office tower in Financial District. Single institutional tenant (financial services firm) with 12 years remaining on lease. Trophy asset.",
    creditBoxNotes: "Top-tier institutional-quality asset. IG-rated tenant covenant. DSCR of 1.62x substantially above floor. Very strong deal.",
    loiRecommended: true, loiIssuedDate: dateStr(2025, 10, 1), loiExpirationDate: dateStr(2025, 11, 1),
    applicationDepositAmountUsd: "75,000", applicationDepositDate: dateStr(2025, 10, 20),
    signedLoiDate: dateStr(2025, 10, 15), debitAuthorizationDate: dateStr(2025, 10, 20),
    rateLockEnabled: true, rateLockRatePct: "5.85", rateLockExpirationDate: dateStr(2026, 4, 1),
    appraisalOrderedDate: dateStr(2025, 10, 22), appraisalCompletedDate: dateStr(2025, 12, 5),
    appraisalValueUsd: "76,500,000", environmentalStatus: "Clear", borrowerFormsStatus: "Received",
    commitmentLetterRecommended: true, commitmentLetterIssuedDate: dateStr(2026, 1, 8),
    conditionalApprovals: "Borrower to certify no material change in tenant financial condition\nLender's counsel to confirm no adverse title matters",
    creditRiskExceptions: "",
    hmdaComplete: true, hmdaNotes: "HMDA complete 1/15.",
    insuranceCarrier: "AIG Property Casualty", insurancePolicyNumber: "AIG-2026-0013488",
    insuranceEffectiveDate: dateStr(2026, 3, 24),
    titleCompany: "Stewart Title Guaranty Company",
    escrowCompany: "Stewart Title Guaranty Company",
    floodZoneDesignation: "Zone X",
    titleReportDate: dateStr(2026, 2, 12),
    docsDrawnDate: dateStr(2026, 3, 10), settlementFeesUsd: "82,000",
    settlementStatementDate: dateStr(2026, 3, 10),
    docsBackDate: dateStr(2026, 3, 17), titleConfirmationDate: dateStr(2026, 3, 17),
    wireAmountUsd: "41,682,000", wireBankName: "JPMorgan Chase Bank, N.A.",
    wireAbaNumber: "021000021", wireAccountNumber: "****4471",
    servicingLoanNumber: "JPM-CRE-2026-041600", bookingDate: dateStr(2026, 3, 24),
    comments: [
      { id: uid("c10a"), applicationId: uid("a10"), parentCommentId: null, author: "Marcus Hill (Closing)", text: "Wire instructions verified with borrower via phone. Funding scheduled for 3/24 at 10am ET.", createdAt: dt(2026, 3, 21) },
      { id: uid("c10b"), applicationId: uid("a10"), parentCommentId: uid("c10a"), author: "Priya Nair (CRO)", text: "Confirmed. Notify servicing team to book to portfolio once wire confirms.", createdAt: dt(2026, 3, 21) },
    ],
    attachments: [],
  },

  // ── 11. Inquiry — Industrial Houston (second Inquiry) ─────────────────────────
  {
    id: uid("a11"), createdAt: dt(2026, 3, 20), updatedAt: dt(2026, 3, 20),
    status: "Inquiry",
    borrowerId: uid("b05"), propertyId: uid("p11"),
    loanType: "Acquisition", loanAmountUsd: "24,000,000", loanTermYears: "10",
    interestType: "Fixed", interestRatePct: "", amortizationType: "Full Amortizing",
    ltvPct: "60", dscrRatio: "", targetClosingDate: dateStr(2026, 8, 30),
    inquiryNotes: "Single-tenant NNN industrial near Bush Intercontinental Airport. 100% leased to publicly-traded logistics company, 8 years remaining on lease. Asking $40M. Excellent credit tenant.",
    creditBoxNotes: "", loiRecommended: false, loiIssuedDate: "", loiExpirationDate: "",
    applicationDepositAmountUsd: "", applicationDepositDate: "", signedLoiDate: "",
    debitAuthorizationDate: "", rateLockEnabled: false, rateLockRatePct: "", rateLockExpirationDate: "",
    appraisalOrderedDate: "", appraisalCompletedDate: "", appraisalValueUsd: "",
    environmentalStatus: "", borrowerFormsStatus: "",
    commitmentLetterRecommended: false, commitmentLetterIssuedDate: "",
    conditionalApprovals: "", creditRiskExceptions: "",
    hmdaComplete: false, hmdaNotes: "",
    insuranceCarrier: "", insurancePolicyNumber: "", insuranceEffectiveDate: "",
    titleCompany: "", escrowCompany: "", floodZoneDesignation: "", titleReportDate: "",
    docsDrawnDate: "", settlementFeesUsd: "", settlementStatementDate: "",
    docsBackDate: "", titleConfirmationDate: "",
    wireAmountUsd: "", wireBankName: "", wireAbaNumber: "", wireAccountNumber: "",
    servicingLoanNumber: "", bookingDate: "",
    comments: [],
    attachments: [],
  },

  // ── 12. Application Processing — Self Storage Phoenix ─────────────────────────
  {
    id: uid("a12"), createdAt: dt(2026, 2, 1), updatedAt: dt(2026, 3, 16),
    status: "Application Processing",
    borrowerId: uid("b06"), propertyId: uid("p12"),
    loanType: "Refinance", loanAmountUsd: "6,200,000", loanTermYears: "10",
    interestType: "Fixed", interestRatePct: "6.60", amortizationType: "Full Amortizing",
    ltvPct: "62", dscrRatio: "1.48", targetClosingDate: dateStr(2026, 5, 30),
    inquiryNotes: "Class A self-storage facility in growing Arcadia submarket. 480 climate-controlled units, 88% physical occupancy. Digital-native operation with strong NOI.",
    creditBoxNotes: "Self-storage sector performing well nationally. NOI growth 8% YoY. DSCR comfortably above 1.35x floor. Recommend LOI.",
    loiRecommended: true, loiIssuedDate: dateStr(2026, 2, 14), loiExpirationDate: dateStr(2026, 3, 14),
    applicationDepositAmountUsd: "10,000", applicationDepositDate: dateStr(2026, 3, 1),
    signedLoiDate: dateStr(2026, 2, 28), debitAuthorizationDate: dateStr(2026, 3, 1),
    rateLockEnabled: false, rateLockRatePct: "", rateLockExpirationDate: "",
    appraisalOrderedDate: dateStr(2026, 3, 5), appraisalCompletedDate: "",
    appraisalValueUsd: "", environmentalStatus: "Ordered", borrowerFormsStatus: "Packaged",
    commitmentLetterRecommended: false, commitmentLetterIssuedDate: "",
    conditionalApprovals: "", creditRiskExceptions: "",
    hmdaComplete: false, hmdaNotes: "",
    insuranceCarrier: "", insurancePolicyNumber: "", insuranceEffectiveDate: "",
    titleCompany: "", escrowCompany: "", floodZoneDesignation: "", titleReportDate: "",
    docsDrawnDate: "", settlementFeesUsd: "", settlementStatementDate: "",
    docsBackDate: "", titleConfirmationDate: "",
    wireAmountUsd: "", wireBankName: "", wireAbaNumber: "", wireAccountNumber: "",
    servicingLoanNumber: "", bookingDate: "",
    comments: [
      { id: uid("c12a"), applicationId: uid("a12"), parentCommentId: null, author: "Lisa Park (Processing)", text: "Appraisal ordered 3/5. Will take ~3 weeks. Borrower packaging financial statements.", createdAt: dt(2026, 3, 5) },
    ],
    attachments: [],
  },
];
