import type {
  Borrower,
  Condition,
  Exception,
  LOAApplication,
  OperatingYear,
  Property,
  RentRollUnit,
} from "@/context/ApplicationContext";

function uid(seed: string): string {
  return `seed_${seed}`;
}

function dt(y: number, m: number, d: number): string {
  return new Date(y, m - 1, d).toISOString();
}

function dateStr(y: number, m: number, d: number): string {
  return `${String(m).padStart(2, "0")}/${String(d).padStart(2, "0")}/${y}`;
}

// ─── Borrowers ────────────────────────────────────────────────────────────────

export const SEED_BORROWERS: Borrower[] = [
  {
    id: uid("b01"), createdAt: dt(2026, 1, 5), updatedAt: dt(2026, 2, 10),
    firstName: "James", lastName: "Hartley", entityName: "Hartley Capital Partners LLC",
    email: "j.hartley@hartleycap.com", phone: "(212) 555-0181",
    creExperienceYears: "18", netWorthUsd: "24,500,000", liquidityUsd: "4,200,000",
    creditScore: "748",
  },
  {
    id: uid("b02"), createdAt: dt(2026, 1, 12), updatedAt: dt(2026, 2, 15),
    firstName: "Maria", lastName: "Santos", entityName: "Santos Real Estate Group Inc",
    email: "msantos@sreg.com", phone: "(213) 555-0247",
    creExperienceYears: "14", netWorthUsd: "18,000,000", liquidityUsd: "2,800,000",
    creditScore: "761",
  },
  {
    id: uid("b03"), createdAt: dt(2026, 1, 20), updatedAt: dt(2026, 3, 1),
    firstName: "David", lastName: "Chen", entityName: "Chen Properties LLC",
    email: "dchen@chenproperties.com", phone: "(415) 555-0312",
    creExperienceYears: "22", netWorthUsd: "41,000,000", liquidityUsd: "7,500,000",
    creditScore: "782",
  },
  {
    id: uid("b04"), createdAt: dt(2026, 2, 3), updatedAt: dt(2026, 3, 8),
    firstName: "Rachel", lastName: "Kim", entityName: "Meridian Investments Group",
    email: "rkim@meridian-inv.com", phone: "(312) 555-0499",
    creExperienceYears: "11", netWorthUsd: "12,750,000", liquidityUsd: "1,900,000",
    creditScore: "733",
  },
  {
    id: uid("b05"), createdAt: dt(2026, 2, 10), updatedAt: dt(2026, 3, 5),
    firstName: "Thomas", lastName: "Brooks", entityName: "Brooks & Associates CRE",
    email: "tbrooks@brooksassoc.com", phone: "(713) 555-0560",
    creExperienceYears: "9", netWorthUsd: "8,200,000", liquidityUsd: "1,100,000",
    creditScore: "719",
  },
  {
    id: uid("b06"), createdAt: dt(2026, 2, 18), updatedAt: dt(2026, 3, 12),
    firstName: "Sarah", lastName: "Mitchell", entityName: "Mitchell Commercial Real Estate LLC",
    email: "smitchell@mitchellcre.com", phone: "(305) 555-0623",
    creExperienceYears: "16", netWorthUsd: "31,000,000", liquidityUsd: "5,400,000",
    creditScore: "769",
  },
  {
    id: uid("b07"), createdAt: dt(2026, 1, 28), updatedAt: dt(2026, 3, 15),
    firstName: "Robert", lastName: "Nguyen", entityName: "Pacific Coast Holdings Corp",
    email: "rnguyen@paccoasthold.com", phone: "(949) 555-0778",
    creExperienceYears: "20", netWorthUsd: "55,000,000", liquidityUsd: "9,100,000",
    creditScore: "795",
  },
  {
    id: uid("b08"), createdAt: dt(2026, 3, 2), updatedAt: dt(2026, 3, 20),
    firstName: "Evelyn", lastName: "Carter", entityName: "Carter Development Corporation",
    email: "ecarter@carterdevelopment.com", phone: "(512) 555-0834",
    creExperienceYears: "7", netWorthUsd: "6,500,000", liquidityUsd: "900,000",
    creditScore: "",  // Not yet at Application Start — ECOA compliant
  },
];

// ─── Properties ───────────────────────────────────────────────────────────────

export const SEED_PROPERTIES: Property[] = [
  {
    id: uid("p01"), createdAt: dt(2026, 1, 5), updatedAt: dt(2026, 2, 10),
    streetAddress: "1200 Market Street", city: "Philadelphia", state: "PA", zipCode: "19107",
    propertyType: "Office", grossSqFt: "124,000", numberOfUnits: "", yearBuilt: "2004",
    physicalOccupancyPct: "88", economicOccupancyPct: "85",
  },
  {
    id: uid("p02"), createdAt: dt(2026, 1, 12), updatedAt: dt(2026, 2, 15),
    streetAddress: "850 Fifth Avenue", city: "New York", state: "NY", zipCode: "10065",
    propertyType: "Retail", grossSqFt: "36,500", numberOfUnits: "12", yearBuilt: "1998",
    physicalOccupancyPct: "92", economicOccupancyPct: "89",
  },
  {
    id: uid("p03"), createdAt: dt(2026, 1, 20), updatedAt: dt(2026, 3, 1),
    streetAddress: "4400 Industrial Boulevard", city: "Atlanta", state: "GA", zipCode: "30336",
    propertyType: "Industrial", grossSqFt: "312,000", numberOfUnits: "", yearBuilt: "2011",
    physicalOccupancyPct: "95", economicOccupancyPct: "94",
  },
  {
    id: uid("p04"), createdAt: dt(2026, 2, 3), updatedAt: dt(2026, 3, 8),
    streetAddress: "2800 Wilshire Boulevard", city: "Los Angeles", state: "CA", zipCode: "90057",
    propertyType: "Multifamily", grossSqFt: "98,400", numberOfUnits: "120", yearBuilt: "2016",
    physicalOccupancyPct: "96", economicOccupancyPct: "93",
  },
  {
    id: uid("p05"), createdAt: dt(2026, 2, 10), updatedAt: dt(2026, 3, 5),
    streetAddress: "330 North Michigan Avenue", city: "Chicago", state: "IL", zipCode: "60601",
    propertyType: "Mixed Use", grossSqFt: "78,200", numberOfUnits: "48", yearBuilt: "2008",
    physicalOccupancyPct: "91", economicOccupancyPct: "88",
  },
  {
    id: uid("p06"), createdAt: dt(2026, 2, 18), updatedAt: dt(2026, 3, 12),
    streetAddress: "600 Congress Avenue", city: "Austin", state: "TX", zipCode: "78701",
    propertyType: "Office", grossSqFt: "55,000", numberOfUnits: "", yearBuilt: "2019",
    physicalOccupancyPct: "82", economicOccupancyPct: "80",
  },
  {
    id: uid("p07"), createdAt: dt(2026, 1, 28), updatedAt: dt(2026, 3, 15),
    streetAddress: "1500 Brickell Avenue", city: "Miami", state: "FL", zipCode: "33131",
    propertyType: "Hotel", grossSqFt: "145,000", numberOfUnits: "218", yearBuilt: "2014",
    physicalOccupancyPct: "79", economicOccupancyPct: "74",
  },
  {
    id: uid("p08"), createdAt: dt(2026, 2, 5), updatedAt: dt(2026, 3, 10),
    streetAddress: "3200 Peachtree Road NE", city: "Atlanta", state: "GA", zipCode: "30305",
    propertyType: "Multifamily", grossSqFt: "182,000", numberOfUnits: "224", yearBuilt: "2018",
    physicalOccupancyPct: "97", economicOccupancyPct: "95",
  },
  {
    id: uid("p09"), createdAt: dt(2026, 2, 22), updatedAt: dt(2026, 3, 18),
    streetAddress: "900 North Michigan Avenue", city: "Chicago", state: "IL", zipCode: "60611",
    propertyType: "Retail", grossSqFt: "44,600", numberOfUnits: "8", yearBuilt: "2001",
    physicalOccupancyPct: "100", economicOccupancyPct: "97",
  },
  {
    id: uid("p10"), createdAt: dt(2026, 1, 15), updatedAt: dt(2026, 3, 20),
    streetAddress: "555 California Street", city: "San Francisco", state: "CA", zipCode: "94104",
    propertyType: "Office", grossSqFt: "208,000", numberOfUnits: "", yearBuilt: "2007",
    physicalOccupancyPct: "86", economicOccupancyPct: "83",
  },
  {
    id: uid("p11"), createdAt: dt(2026, 3, 1), updatedAt: dt(2026, 3, 18),
    streetAddress: "7800 Airport Boulevard", city: "Houston", state: "TX", zipCode: "77061",
    propertyType: "Industrial", grossSqFt: "425,000", numberOfUnits: "", yearBuilt: "2015",
    physicalOccupancyPct: "100", economicOccupancyPct: "100",
  },
  {
    id: uid("p12"), createdAt: dt(2026, 3, 8), updatedAt: dt(2026, 3, 20),
    streetAddress: "2100 East Camelback Road", city: "Phoenix", state: "AZ", zipCode: "85016",
    propertyType: "Self Storage", grossSqFt: "62,000", numberOfUnits: "480", yearBuilt: "2020",
    physicalOccupancyPct: "88", economicOccupancyPct: "86",
  },
];

// ─── Applications ─────────────────────────────────────────────────────────────
// NOTE: conditionalApprovals and creditRiskExceptions have been removed from
// LOAApplication. They are now 3NF entities: Condition[] and Exception[].

export const SEED_APPLICATIONS: LOAApplication[] = [
  // ── 1. Inquiry — Office Philadelphia ─────────────────────────────────────────
  {
    id: uid("a01"), createdAt: dt(2026, 3, 14), updatedAt: dt(2026, 3, 14),
    status: "Inquiry",
    borrowerId: uid("b08"), propertyId: uid("p01"),
    loanType: "Acquisition", loanAmountUsd: "8,500,000", loanTermYears: "10",
    interestType: "Fixed", interestRatePct: "6.75", amortizationType: "Full Amortizing",
    ltvPct: "65", dscrRatio: "1.28", targetClosingDate: dateStr(2026, 7, 15),
    inquiryNotes: "Borrower is exploring acquisition of stabilized office building in Center City. Has toured the property twice. Asking price $13M. Looking for 65% LTV conventional financing. Market is recovering post-COVID — occupancy trending up from 82% to 88%.",
    creditBoxNotes: "", loiRecommended: false, loiIssuedDate: "", loiExpirationDate: "",
    applicationDepositAmountUsd: "", applicationDepositDate: "", signedLoiDate: "",
    debitAuthorizationDate: "", rateLockEnabled: false, rateLockRatePct: "", rateLockExpirationDate: "",
    appraisalOrderedDate: "", appraisalCompletedDate: "", appraisalValueUsd: "",
    environmentalStatus: "", borrowerFormsStatus: "",
    commitmentLetterRecommended: false, commitmentLetterIssuedDate: "",
    hmdaComplete: false, hmdaNotes: "",
    insuranceCarrier: "", insurancePolicyNumber: "", insuranceEffectiveDate: "",
    titleCompany: "", escrowCompany: "", floodZoneDesignation: "", titleReportDate: "",
    docsDrawnDate: "", settlementFeesUsd: "", settlementStatementDate: "",
    docsBackDate: "", titleConfirmationDate: "",
    wireAmountUsd: "", wireBankName: "", wireAbaNumber: "", wireAccountNumber: "",
    servicingLoanNumber: "", bookingDate: "",
    comments: [
      { id: uid("c01a"), applicationId: uid("a01"), parentCommentId: null, author: "Jennifer Walsh (Sales)", text: "Initial call with borrower went well. Strong equity position and long track record in Philly office market.", createdAt: dt(2026, 3, 14) },
    ],
    attachments: [],
  },

  // ── 2. Initial Credit Review — Retail New York ──────────────────────────────────
  {
    id: uid("a02"), createdAt: dt(2026, 2, 20), updatedAt: dt(2026, 3, 5),
    status: "Initial Credit Review",
    borrowerId: uid("b04"), propertyId: uid("p02"),
    loanType: "Refinance", loanAmountUsd: "12,200,000", loanTermYears: "7",
    interestType: "Fixed", interestRatePct: "6.40", amortizationType: "Interest Only",
    ltvPct: "60", dscrRatio: "1.45", targetClosingDate: dateStr(2026, 6, 30),
    inquiryNotes: "Borrower seeking cash-out refinance on flagship retail property in Midtown. Current loan maturity in August. Strong anchor tenant (national pharmacy chain) with 9 years remaining on NNN lease.",
    creditBoxNotes: "Deal fits credit box well. Cap rate of 5.2% aligns with market. Anchor tenant NNN lease provides strong debt service coverage. IO period justified given lease term remaining. Recommend LOI.",
    loiRecommended: true, loiIssuedDate: dateStr(2026, 3, 5), loiExpirationDate: dateStr(2026, 4, 5),
    applicationDepositAmountUsd: "", applicationDepositDate: "", signedLoiDate: "",
    debitAuthorizationDate: "", rateLockEnabled: false, rateLockRatePct: "", rateLockExpirationDate: "",
    appraisalOrderedDate: "", appraisalCompletedDate: "", appraisalValueUsd: "",
    environmentalStatus: "", borrowerFormsStatus: "",
    commitmentLetterRecommended: false, commitmentLetterIssuedDate: "",
    hmdaComplete: false, hmdaNotes: "",
    insuranceCarrier: "", insurancePolicyNumber: "", insuranceEffectiveDate: "",
    titleCompany: "", escrowCompany: "", floodZoneDesignation: "", titleReportDate: "",
    docsDrawnDate: "", settlementFeesUsd: "", settlementStatementDate: "",
    docsBackDate: "", titleConfirmationDate: "",
    wireAmountUsd: "", wireBankName: "", wireAbaNumber: "", wireAccountNumber: "",
    servicingLoanNumber: "", bookingDate: "",
    comments: [
      { id: uid("c02a"), applicationId: uid("a02"), parentCommentId: null, author: "Alan Morse (Credit Risk)", text: "LOI issued 3/5. Waiting on borrower to review terms and execute.", createdAt: dt(2026, 3, 5) },
      { id: uid("c02b"), applicationId: uid("a02"), parentCommentId: uid("c02a"), author: "Jennifer Walsh (Sales)", text: "Borrower confirmed receipt. Expects to sign by 3/12.", createdAt: dt(2026, 3, 6) },
    ],
    attachments: [],
  },

  // ── 3. Application Start — Industrial Atlanta ────────────────────────────────
  {
    id: uid("a03"), createdAt: dt(2026, 2, 5), updatedAt: dt(2026, 3, 10),
    status: "Application Start",
    borrowerId: uid("b01"), propertyId: uid("p03"),
    loanType: "Acquisition", loanAmountUsd: "19,500,000", loanTermYears: "10",
    interestType: "Fixed", interestRatePct: "6.20", amortizationType: "Full Amortizing",
    ltvPct: "62", dscrRatio: "1.52", targetClosingDate: dateStr(2026, 5, 30),
    inquiryNotes: "Class A industrial acquisition near Hartsfield-Jackson. Two NNN tenants — logistics company and e-commerce fulfillment. Excellent location fundamentals.",
    creditBoxNotes: "Strong industrial fundamentals. 95% physical occupancy with long-term tenants. Fits core credit box. DSCR well above 1.35x floor. Recommend LOI.",
    loiRecommended: true, loiIssuedDate: dateStr(2026, 2, 15), loiExpirationDate: dateStr(2026, 3, 15),
    applicationDepositAmountUsd: "25,000", applicationDepositDate: dateStr(2026, 3, 8),
    signedLoiDate: dateStr(2026, 3, 2), debitAuthorizationDate: dateStr(2026, 3, 8),
    rateLockEnabled: false, rateLockRatePct: "", rateLockExpirationDate: "",
    appraisalOrderedDate: "", appraisalCompletedDate: "", appraisalValueUsd: "",
    environmentalStatus: "", borrowerFormsStatus: "Not Started",
    commitmentLetterRecommended: false, commitmentLetterIssuedDate: "",
    hmdaComplete: false, hmdaNotes: "",
    insuranceCarrier: "", insurancePolicyNumber: "", insuranceEffectiveDate: "",
    titleCompany: "", escrowCompany: "", floodZoneDesignation: "", titleReportDate: "",
    docsDrawnDate: "", settlementFeesUsd: "", settlementStatementDate: "",
    docsBackDate: "", titleConfirmationDate: "",
    wireAmountUsd: "", wireBankName: "", wireAbaNumber: "", wireAccountNumber: "",
    servicingLoanNumber: "", bookingDate: "",
    comments: [
      { id: uid("c03a"), applicationId: uid("a03"), parentCommentId: null, author: "Jennifer Walsh (Sales)", text: "Deposit received 3/8. Debit auth also signed. Kicking off application package.", createdAt: dt(2026, 3, 10) },
    ],
    attachments: [],
  },

  // ── 4. Application Processing — Multifamily LA ───────────────────────────────
  {
    id: uid("a04"), createdAt: dt(2026, 1, 15), updatedAt: dt(2026, 3, 18),
    status: "Application Processing",
    borrowerId: uid("b02"), propertyId: uid("p04"),
    loanType: "Refinance", loanAmountUsd: "22,400,000", loanTermYears: "10",
    interestType: "Fixed", interestRatePct: "6.00", amortizationType: "Full Amortizing",
    ltvPct: "58", dscrRatio: "1.60", targetClosingDate: dateStr(2026, 5, 15),
    inquiryNotes: "Multifamily refinance of 120-unit complex in Koreatown. Current loan at 5.5% maturing in June. Borrower wants to lock in current rate before further market movement.",
    creditBoxNotes: "96% occupancy well above 90% hurdle. DSCR of 1.60x provides strong cushion. LA multifamily fundamentals remain robust. Recommend LOI.",
    loiRecommended: true, loiIssuedDate: dateStr(2026, 2, 1), loiExpirationDate: dateStr(2026, 3, 1),
    applicationDepositAmountUsd: "30,000", applicationDepositDate: dateStr(2026, 2, 20),
    signedLoiDate: dateStr(2026, 2, 15), debitAuthorizationDate: dateStr(2026, 2, 20),
    rateLockEnabled: false, rateLockRatePct: "", rateLockExpirationDate: "",
    appraisalOrderedDate: dateStr(2026, 3, 1), appraisalCompletedDate: "",
    appraisalValueUsd: "", environmentalStatus: "In Progress", borrowerFormsStatus: "Packaged",
    commitmentLetterRecommended: false, commitmentLetterIssuedDate: "",
    hmdaComplete: false, hmdaNotes: "",
    insuranceCarrier: "", insurancePolicyNumber: "", insuranceEffectiveDate: "",
    titleCompany: "", escrowCompany: "", floodZoneDesignation: "", titleReportDate: "",
    docsDrawnDate: "", settlementFeesUsd: "", settlementStatementDate: "",
    docsBackDate: "", titleConfirmationDate: "",
    wireAmountUsd: "", wireBankName: "", wireAbaNumber: "", wireAccountNumber: "",
    servicingLoanNumber: "", bookingDate: "",
    comments: [
      { id: uid("c04a"), applicationId: uid("a04"), parentCommentId: null, author: "Lisa Park (Processing)", text: "Appraisal ordered 3/1 with Pacific Valuation Group. Est. completion 3/28.", createdAt: dt(2026, 3, 1) },
      { id: uid("c04b"), applicationId: uid("a04"), parentCommentId: null, author: "Lisa Park (Processing)", text: "Phase I Environmental ordered. Awaiting site access confirmation.", createdAt: dt(2026, 3, 8) },
    ],
    attachments: [],
  },

  // ── 5. Final Credit Review — Mixed Use Chicago ───────────────────────────────
  {
    id: uid("a05"), createdAt: dt(2026, 1, 8), updatedAt: dt(2026, 3, 19),
    status: "Final Credit Review",
    borrowerId: uid("b07"), propertyId: uid("p05"),
    loanType: "Acquisition", loanAmountUsd: "15,750,000", loanTermYears: "10",
    interestType: "Floating", interestRatePct: "7.10", amortizationType: "Partial IO",
    ltvPct: "63", dscrRatio: "1.38", targetClosingDate: dateStr(2026, 4, 30),
    inquiryNotes: "Mixed-use asset in Streeterville. Ground floor retail (2 units) + 48 residential apartments above. Strong River North submarket fundamentals.",
    creditBoxNotes: "Mixed-use with residential majority qualifies under multifamily program. Floating rate with 3yr IO is appropriate for value-add business plan. Recommend LOI with conditions.",
    loiRecommended: true, loiIssuedDate: dateStr(2026, 1, 20), loiExpirationDate: dateStr(2026, 2, 20),
    applicationDepositAmountUsd: "20,000", applicationDepositDate: dateStr(2026, 2, 5),
    signedLoiDate: dateStr(2026, 2, 3), debitAuthorizationDate: dateStr(2026, 2, 5),
    rateLockEnabled: true, rateLockRatePct: "7.10", rateLockExpirationDate: dateStr(2026, 5, 15),
    appraisalOrderedDate: dateStr(2026, 2, 8), appraisalCompletedDate: dateStr(2026, 3, 5),
    appraisalValueUsd: "25,100,000", environmentalStatus: "Clear", borrowerFormsStatus: "Received",
    commitmentLetterRecommended: false, commitmentLetterIssuedDate: "",
    hmdaComplete: false, hmdaNotes: "",
    insuranceCarrier: "", insurancePolicyNumber: "", insuranceEffectiveDate: "",
    titleCompany: "", escrowCompany: "", floodZoneDesignation: "", titleReportDate: "",
    docsDrawnDate: "", settlementFeesUsd: "", settlementStatementDate: "",
    docsBackDate: "", titleConfirmationDate: "",
    wireAmountUsd: "", wireBankName: "", wireAbaNumber: "", wireAccountNumber: "",
    servicingLoanNumber: "", bookingDate: "",
    comments: [
      { id: uid("c05a"), applicationId: uid("a05"), parentCommentId: null, author: "Alan Morse (Credit Risk)", text: "Credit memo drafted and under review with CRO. Appraisal came in at $25.1M — slightly above purchase price. Good news.", createdAt: dt(2026, 3, 18) },
      { id: uid("c05b"), applicationId: uid("a05"), parentCommentId: uid("c05a"), author: "Priya Nair (CRO)", text: "Reviewed. Floating rate exception approved. Proceeding to CL recommendation.", createdAt: dt(2026, 3, 19) },
    ],
    attachments: [],
  },

  // ── 6. Pre-close — Office Austin ─────────────────────────────────────────────
  {
    id: uid("a06"), createdAt: dt(2025, 12, 10), updatedAt: dt(2026, 3, 20),
    status: "Pre-close",
    borrowerId: uid("b06"), propertyId: uid("p06"),
    loanType: "Acquisition", loanAmountUsd: "9,800,000", loanTermYears: "10",
    interestType: "Fixed", interestRatePct: "6.55", amortizationType: "Full Amortizing",
    ltvPct: "65", dscrRatio: "1.41", targetClosingDate: dateStr(2026, 4, 15),
    inquiryNotes: "Tech-leased office building in downtown Austin. Single tenant NNN — 5 years remaining. Borrower has existing relationship with bank.",
    creditBoxNotes: "Single tenant risk noted but offset by strong covenant. DSCR above floor. Recommend LOI.",
    loiRecommended: true, loiIssuedDate: dateStr(2025, 12, 28), loiExpirationDate: dateStr(2026, 1, 28),
    applicationDepositAmountUsd: "15,000", applicationDepositDate: dateStr(2026, 1, 20),
    signedLoiDate: dateStr(2026, 1, 15), debitAuthorizationDate: dateStr(2026, 1, 20),
    rateLockEnabled: true, rateLockRatePct: "6.55", rateLockExpirationDate: dateStr(2026, 4, 30),
    appraisalOrderedDate: dateStr(2026, 1, 22), appraisalCompletedDate: dateStr(2026, 2, 18),
    appraisalValueUsd: "15,200,000", environmentalStatus: "Clear", borrowerFormsStatus: "Received",
    commitmentLetterRecommended: true, commitmentLetterIssuedDate: dateStr(2026, 3, 10),
    hmdaComplete: false, hmdaNotes: "HMDA LAR fields 90% complete — still need census tract code and action taken date.",
    insuranceCarrier: "", insurancePolicyNumber: "", insuranceEffectiveDate: "",
    titleCompany: "", escrowCompany: "", floodZoneDesignation: "", titleReportDate: "",
    docsDrawnDate: "", settlementFeesUsd: "", settlementStatementDate: "",
    docsBackDate: "", titleConfirmationDate: "",
    wireAmountUsd: "", wireBankName: "", wireAbaNumber: "", wireAccountNumber: "",
    servicingLoanNumber: "", bookingDate: "",
    comments: [
      { id: uid("c06a"), applicationId: uid("a06"), parentCommentId: null, author: "Lisa Park (Processing)", text: "HMDA nearly complete — missing census tract. Requesting from GIS team.", createdAt: dt(2026, 3, 20) },
    ],
    attachments: [],
  },

  // ── 7. Ready for Docs — Hotel Miami ──────────────────────────────────────────
  {
    id: uid("a07"), createdAt: dt(2025, 11, 5), updatedAt: dt(2026, 3, 15),
    status: "Ready for Docs",
    borrowerId: uid("b07"), propertyId: uid("p07"),
    loanType: "Refinance", loanAmountUsd: "28,500,000", loanTermYears: "5",
    interestType: "Floating", interestRatePct: "7.45", amortizationType: "Interest Only",
    ltvPct: "55", dscrRatio: "1.32", targetClosingDate: dateStr(2026, 4, 10),
    inquiryNotes: "Boutique hotel refinance on Brickell Avenue. Post-renovation stabilization complete. Strong ADR and RevPAR metrics for the submarket.",
    creditBoxNotes: "Hotel sector exception required. Post-renovation performance data reviewed. Revenue trending above underwriting. IO approved for 5yr term.",
    loiRecommended: true, loiIssuedDate: dateStr(2025, 11, 25), loiExpirationDate: dateStr(2025, 12, 25),
    applicationDepositAmountUsd: "50,000", applicationDepositDate: dateStr(2025, 12, 18),
    signedLoiDate: dateStr(2025, 12, 15), debitAuthorizationDate: dateStr(2025, 12, 18),
    rateLockEnabled: true, rateLockRatePct: "7.45", rateLockExpirationDate: dateStr(2026, 4, 30),
    appraisalOrderedDate: dateStr(2026, 1, 5), appraisalCompletedDate: dateStr(2026, 2, 10),
    appraisalValueUsd: "52,000,000", environmentalStatus: "Clear", borrowerFormsStatus: "Received",
    commitmentLetterRecommended: true, commitmentLetterIssuedDate: dateStr(2026, 2, 28),
    hmdaComplete: true, hmdaNotes: "HMDA complete. All LAR fields verified 3/12.",
    insuranceCarrier: "Chubb Insurance Company", insurancePolicyNumber: "CHB-2026-0078341",
    insuranceEffectiveDate: dateStr(2026, 4, 10),
    titleCompany: "Chicago Title Insurance Company",
    escrowCompany: "First American Title",
    floodZoneDesignation: "Zone X",
    titleReportDate: dateStr(2026, 3, 10),
    docsDrawnDate: "", settlementFeesUsd: "", settlementStatementDate: "",
    docsBackDate: "", titleConfirmationDate: "",
    wireAmountUsd: "", wireBankName: "", wireAbaNumber: "", wireAccountNumber: "",
    servicingLoanNumber: "", bookingDate: "",
    comments: [
      { id: uid("c07a"), applicationId: uid("a07"), parentCommentId: null, author: "Marcus Hill (Closing)", text: "All third-party items confirmed. Title report clean. Ready to request docs.", createdAt: dt(2026, 3, 15) },
    ],
    attachments: [],
  },

  // ── 8. Docs Drawn — Multifamily Atlanta ──────────────────────────────────────
  {
    id: uid("a08"), createdAt: dt(2025, 10, 20), updatedAt: dt(2026, 3, 18),
    status: "Docs Drawn",
    borrowerId: uid("b03"), propertyId: uid("p08"),
    loanType: "Acquisition", loanAmountUsd: "32,100,000", loanTermYears: "10",
    interestType: "Fixed", interestRatePct: "5.95", amortizationType: "Full Amortizing",
    ltvPct: "60", dscrRatio: "1.58", targetClosingDate: dateStr(2026, 3, 28),
    inquiryNotes: "224-unit garden-style multifamily in Buckhead. Class A property, 2018 vintage. Seller has accepted offer at $53.5M.",
    creditBoxNotes: "Best-in-class Buckhead multifamily. 97% occupancy, strong rent growth trajectory. DSCR of 1.58x well above floor.",
    loiRecommended: true, loiIssuedDate: dateStr(2025, 11, 5), loiExpirationDate: dateStr(2025, 12, 5),
    applicationDepositAmountUsd: "50,000", applicationDepositDate: dateStr(2025, 11, 25),
    signedLoiDate: dateStr(2025, 11, 20), debitAuthorizationDate: dateStr(2025, 11, 25),
    rateLockEnabled: true, rateLockRatePct: "5.95", rateLockExpirationDate: dateStr(2026, 4, 15),
    appraisalOrderedDate: dateStr(2025, 12, 1), appraisalCompletedDate: dateStr(2026, 1, 12),
    appraisalValueUsd: "53,800,000", environmentalStatus: "Clear", borrowerFormsStatus: "Received",
    commitmentLetterRecommended: true, commitmentLetterIssuedDate: dateStr(2026, 2, 5),
    hmdaComplete: true, hmdaNotes: "HMDA LAR complete and validated 2/28.",
    insuranceCarrier: "Travelers Property Casualty", insurancePolicyNumber: "TRV-2026-0041829",
    insuranceEffectiveDate: dateStr(2026, 3, 28),
    titleCompany: "Fidelity National Title",
    escrowCompany: "Fidelity National Title",
    floodZoneDesignation: "Zone X",
    titleReportDate: dateStr(2026, 2, 20),
    docsDrawnDate: dateStr(2026, 3, 18), settlementFeesUsd: "48,500",
    settlementStatementDate: dateStr(2026, 3, 18),
    docsBackDate: "", titleConfirmationDate: "",
    wireAmountUsd: "", wireBankName: "", wireAbaNumber: "", wireAccountNumber: "",
    servicingLoanNumber: "", bookingDate: "",
    comments: [
      { id: uid("c08a"), applicationId: uid("a08"), parentCommentId: null, author: "Marcus Hill (Closing)", text: "Loan documents generated and sent to borrower's counsel. Expecting execution by 3/22.", createdAt: dt(2026, 3, 18) },
    ],
    attachments: [],
  },

  // ── 9. Docs Back — Retail Chicago ────────────────────────────────────────────
  {
    id: uid("a09"), createdAt: dt(2025, 10, 1), updatedAt: dt(2026, 3, 20),
    status: "Docs Back",
    borrowerId: uid("b04"), propertyId: uid("p09"),
    loanType: "Refinance", loanAmountUsd: "17,800,000", loanTermYears: "7",
    interestType: "Fixed", interestRatePct: "6.15", amortizationType: "Interest Only",
    ltvPct: "58", dscrRatio: "1.55", targetClosingDate: dateStr(2026, 3, 26),
    inquiryNotes: "Iconic Michigan Avenue retail — 100% occupied with mix of luxury and fashion tenants. National credit tenants on long-term leases.",
    creditBoxNotes: "Trophy retail asset on premier US shopping corridor. 100% occupancy, all national credit tenants. Very low risk profile.",
    loiRecommended: true, loiIssuedDate: dateStr(2025, 10, 20), loiExpirationDate: dateStr(2025, 11, 20),
    applicationDepositAmountUsd: "25,000", applicationDepositDate: dateStr(2025, 11, 10),
    signedLoiDate: dateStr(2025, 11, 5), debitAuthorizationDate: dateStr(2025, 11, 10),
    rateLockEnabled: true, rateLockRatePct: "6.15", rateLockExpirationDate: dateStr(2026, 4, 1),
    appraisalOrderedDate: dateStr(2025, 11, 12), appraisalCompletedDate: dateStr(2025, 12, 20),
    appraisalValueUsd: "30,800,000", environmentalStatus: "Clear", borrowerFormsStatus: "Received",
    commitmentLetterRecommended: true, commitmentLetterIssuedDate: dateStr(2026, 1, 15),
    hmdaComplete: true, hmdaNotes: "Complete.",
    insuranceCarrier: "Liberty Mutual Insurance", insurancePolicyNumber: "LM-2026-0095214",
    insuranceEffectiveDate: dateStr(2026, 3, 26),
    titleCompany: "Chicago Title Insurance Company",
    escrowCompany: "Chicago Title Insurance Company",
    floodZoneDesignation: "Zone X",
    titleReportDate: dateStr(2026, 3, 1),
    docsDrawnDate: dateStr(2026, 3, 14), settlementFeesUsd: "32,500",
    settlementStatementDate: dateStr(2026, 3, 14),
    docsBackDate: dateStr(2026, 3, 20), titleConfirmationDate: dateStr(2026, 3, 20),
    wireAmountUsd: "", wireBankName: "", wireAbaNumber: "", wireAccountNumber: "",
    servicingLoanNumber: "", bookingDate: "",
    comments: [
      { id: uid("c09a"), applicationId: uid("a09"), parentCommentId: null, author: "Marcus Hill (Closing)", text: "Signed docs received from borrower's counsel 3/20. Title confirmed. Ready to wire.", createdAt: dt(2026, 3, 20) },
    ],
    attachments: [],
  },

  // ── 10. Closing — Office San Francisco ───────────────────────────────────────
  {
    id: uid("a10"), createdAt: dt(2025, 9, 15), updatedAt: dt(2026, 3, 21),
    status: "Closing",
    borrowerId: uid("b03"), propertyId: uid("p10"),
    loanType: "Refinance", loanAmountUsd: "41,600,000", loanTermYears: "10",
    interestType: "Fixed", interestRatePct: "5.85", amortizationType: "Full Amortizing",
    ltvPct: "55", dscrRatio: "1.62", targetClosingDate: dateStr(2026, 3, 24),
    inquiryNotes: "Class A office tower in Financial District. Single institutional tenant (financial services firm) with 12 years remaining on lease. Trophy asset.",
    creditBoxNotes: "Top-tier institutional-quality asset. IG-rated tenant covenant. DSCR of 1.62x substantially above floor. Very strong deal.",
    loiRecommended: true, loiIssuedDate: dateStr(2025, 10, 1), loiExpirationDate: dateStr(2025, 11, 1),
    applicationDepositAmountUsd: "75,000", applicationDepositDate: dateStr(2025, 10, 20),
    signedLoiDate: dateStr(2025, 10, 15), debitAuthorizationDate: dateStr(2025, 10, 20),
    rateLockEnabled: true, rateLockRatePct: "5.85", rateLockExpirationDate: dateStr(2026, 4, 1),
    appraisalOrderedDate: dateStr(2025, 10, 22), appraisalCompletedDate: dateStr(2025, 12, 5),
    appraisalValueUsd: "76,500,000", environmentalStatus: "Clear", borrowerFormsStatus: "Received",
    commitmentLetterRecommended: true, commitmentLetterIssuedDate: dateStr(2026, 1, 8),
    hmdaComplete: true, hmdaNotes: "HMDA complete 1/15.",
    insuranceCarrier: "AIG Property Casualty", insurancePolicyNumber: "AIG-2026-0013488",
    insuranceEffectiveDate: dateStr(2026, 3, 24),
    titleCompany: "Stewart Title Guaranty Company",
    escrowCompany: "Stewart Title Guaranty Company",
    floodZoneDesignation: "Zone X",
    titleReportDate: dateStr(2026, 2, 12),
    docsDrawnDate: dateStr(2026, 3, 10), settlementFeesUsd: "82,000",
    settlementStatementDate: dateStr(2026, 3, 10),
    docsBackDate: dateStr(2026, 3, 17), titleConfirmationDate: dateStr(2026, 3, 17),
    wireAmountUsd: "41,682,000", wireBankName: "JPMorgan Chase Bank, N.A.",
    wireAbaNumber: "021000021", wireAccountNumber: "****4471",
    servicingLoanNumber: "JPM-CRE-2026-041600", bookingDate: dateStr(2026, 3, 24),
    comments: [
      { id: uid("c10a"), applicationId: uid("a10"), parentCommentId: null, author: "Marcus Hill (Closing)", text: "Wire instructions verified with borrower via phone. Funding scheduled for 3/24 at 10am ET.", createdAt: dt(2026, 3, 21) },
      { id: uid("c10b"), applicationId: uid("a10"), parentCommentId: uid("c10a"), author: "Priya Nair (CRO)", text: "Confirmed. Notify servicing team to book to portfolio once wire confirms.", createdAt: dt(2026, 3, 21) },
    ],
    attachments: [],
  },

  // ── 11. Inquiry — Industrial Houston ─────────────────────────────────────────
  {
    id: uid("a11"), createdAt: dt(2026, 3, 20), updatedAt: dt(2026, 3, 20),
    status: "Inquiry",
    borrowerId: uid("b05"), propertyId: uid("p11"),
    loanType: "Acquisition", loanAmountUsd: "24,000,000", loanTermYears: "10",
    interestType: "Fixed", interestRatePct: "", amortizationType: "Full Amortizing",
    ltvPct: "60", dscrRatio: "", targetClosingDate: dateStr(2026, 8, 30),
    inquiryNotes: "Single-tenant NNN industrial near Bush Intercontinental Airport. 100% leased to publicly-traded logistics company, 8 years remaining on lease. Asking $40M. Excellent credit tenant.",
    creditBoxNotes: "", loiRecommended: false, loiIssuedDate: "", loiExpirationDate: "",
    applicationDepositAmountUsd: "", applicationDepositDate: "", signedLoiDate: "",
    debitAuthorizationDate: "", rateLockEnabled: false, rateLockRatePct: "", rateLockExpirationDate: "",
    appraisalOrderedDate: "", appraisalCompletedDate: "", appraisalValueUsd: "",
    environmentalStatus: "", borrowerFormsStatus: "",
    commitmentLetterRecommended: false, commitmentLetterIssuedDate: "",
    hmdaComplete: false, hmdaNotes: "",
    insuranceCarrier: "", insurancePolicyNumber: "", insuranceEffectiveDate: "",
    titleCompany: "", escrowCompany: "", floodZoneDesignation: "", titleReportDate: "",
    docsDrawnDate: "", settlementFeesUsd: "", settlementStatementDate: "",
    docsBackDate: "", titleConfirmationDate: "",
    wireAmountUsd: "", wireBankName: "", wireAbaNumber: "", wireAccountNumber: "",
    servicingLoanNumber: "", bookingDate: "",
    comments: [],
    attachments: [],
  },

  // ── 12. Application Processing — Self Storage Phoenix ─────────────────────────
  {
    id: uid("a12"), createdAt: dt(2026, 2, 1), updatedAt: dt(2026, 3, 16),
    status: "Application Processing",
    borrowerId: uid("b06"), propertyId: uid("p12"),
    loanType: "Refinance", loanAmountUsd: "6,200,000", loanTermYears: "10",
    interestType: "Fixed", interestRatePct: "6.60", amortizationType: "Full Amortizing",
    ltvPct: "62", dscrRatio: "1.48", targetClosingDate: dateStr(2026, 5, 30),
    inquiryNotes: "Class A self-storage facility in growing Arcadia submarket. 480 climate-controlled units, 88% physical occupancy. Digital-native operation with strong NOI.",
    creditBoxNotes: "Self-storage sector performing well nationally. NOI growth 8% YoY. DSCR comfortably above 1.35x floor. Recommend LOI.",
    loiRecommended: true, loiIssuedDate: dateStr(2026, 2, 14), loiExpirationDate: dateStr(2026, 3, 14),
    applicationDepositAmountUsd: "10,000", applicationDepositDate: dateStr(2026, 3, 1),
    signedLoiDate: dateStr(2026, 2, 28), debitAuthorizationDate: dateStr(2026, 3, 1),
    rateLockEnabled: false, rateLockRatePct: "", rateLockExpirationDate: "",
    appraisalOrderedDate: dateStr(2026, 3, 5), appraisalCompletedDate: "",
    appraisalValueUsd: "", environmentalStatus: "Ordered", borrowerFormsStatus: "Packaged",
    commitmentLetterRecommended: false, commitmentLetterIssuedDate: "",
    hmdaComplete: false, hmdaNotes: "",
    insuranceCarrier: "", insurancePolicyNumber: "", insuranceEffectiveDate: "",
    titleCompany: "", escrowCompany: "", floodZoneDesignation: "", titleReportDate: "",
    docsDrawnDate: "", settlementFeesUsd: "", settlementStatementDate: "",
    docsBackDate: "", titleConfirmationDate: "",
    wireAmountUsd: "", wireBankName: "", wireAbaNumber: "", wireAccountNumber: "",
    servicingLoanNumber: "", bookingDate: "",
    comments: [
      { id: uid("c12a"), applicationId: uid("a12"), parentCommentId: null, author: "Lisa Park (Processing)", text: "Appraisal ordered 3/5. Will take ~3 weeks. Borrower packaging financial statements.", createdAt: dt(2026, 3, 5) },
    ],
    attachments: [],
  },
];

// ─── Conditions (3NF) ─────────────────────────────────────────────────────────
// Sourced from what was formerly the conditionalApprovals string field.
// Any persona can add a condition at any phase.

export const SEED_CONDITIONS: Condition[] = [
  // a05 — Final Credit Review, Mixed Use Chicago
  {
    id: uid("cond_01"), applicationId: uid("a05"),
    createdAt: dt(2026, 1, 20), updatedAt: dt(2026, 3, 18),
    conditionType: "Financial Covenant",
    description: "Borrower to maintain minimum DSCR of 1.25x on a trailing 12-month basis.",
    status: "Pending",
    appliesTo: "Application",
    phaseAddedAt: "Initial Credit Review",
    createdByPersona: "Credit Risk",
  },
  {
    id: uid("cond_02"), applicationId: uid("a05"),
    createdAt: dt(2026, 1, 20), updatedAt: dt(2026, 3, 18),
    conditionType: "Financial Covenant",
    description: "Borrower must maintain a minimum liquidity reserve of $500,000 at all times.",
    status: "Pending",
    appliesTo: "Borrower",
    phaseAddedAt: "Initial Credit Review",
    createdByPersona: "Credit Risk",
  },
  {
    id: uid("cond_03"), applicationId: uid("a05"),
    createdAt: dt(2026, 2, 5), updatedAt: dt(2026, 3, 18),
    conditionType: "Financial Covenant",
    description: "No additional debt to be incurred without prior written lender consent.",
    status: "Pending",
    appliesTo: "Borrower",
    phaseAddedAt: "Application Start",
    createdByPersona: "Credit Risk",
  },

  // a06 — Pre-close, Office Austin
  {
    id: uid("cond_04"), applicationId: uid("a06"),
    createdAt: dt(2026, 1, 20), updatedAt: dt(2026, 3, 10),
    conditionType: "Legal Documentation",
    description: "Borrower to provide final executed lease abstract from tenant prior to closing.",
    status: "Pending",
    appliesTo: "Property",
    phaseAddedAt: "Application Start",
    createdByPersona: "Credit Risk",
  },
  {
    id: uid("cond_05"), applicationId: uid("a06"),
    createdAt: dt(2026, 3, 10), updatedAt: dt(2026, 3, 10),
    conditionType: "Insurance",
    description: "Borrower insurance policy must be bound and in full effect at or before closing date.",
    status: "Pending",
    appliesTo: "Application",
    phaseAddedAt: "Final Credit Review",
    createdByPersona: "Processing",
  },

  // a07 — Ready for Docs, Hotel Miami
  {
    id: uid("cond_06"), applicationId: uid("a07"),
    createdAt: dt(2025, 12, 1), updatedAt: dt(2026, 3, 15),
    conditionType: "Financial Covenant",
    description: "Borrower to maintain DSCR ≥ 1.25x on a trailing 12-month basis throughout loan term.",
    status: "Pending",
    appliesTo: "Application",
    phaseAddedAt: "Initial Credit Review",
    createdByPersona: "Credit Risk",
  },
  {
    id: uid("cond_07"), applicationId: uid("a07"),
    createdAt: dt(2026, 2, 28), updatedAt: dt(2026, 3, 15),
    conditionType: "Account Control",
    description: "Borrower's primary operating account for the property must be maintained at JPMorgan Chase.",
    status: "Pending",
    appliesTo: "Borrower",
    phaseAddedAt: "Final Credit Review",
    createdByPersona: "Credit Risk",
  },
  {
    id: uid("cond_08"), applicationId: uid("a07"),
    createdAt: dt(2026, 2, 28), updatedAt: dt(2026, 3, 15),
    conditionType: "Collateral",
    description: "Borrower to pledge 100% of equity interests in the property-owning entity as additional collateral.",
    status: "Pending",
    appliesTo: "Application",
    phaseAddedAt: "Final Credit Review",
    createdByPersona: "Credit Risk",
  },

  // a08 — Docs Drawn, Multifamily Atlanta
  {
    id: uid("cond_09"), applicationId: uid("a08"),
    createdAt: dt(2025, 11, 20), updatedAt: dt(2026, 2, 5),
    conditionType: "Legal Documentation",
    description: "Borrower to provide a fully executed purchase and sale agreement prior to commitment.",
    status: "Satisfied",
    appliesTo: "Application",
    phaseAddedAt: "Application Start",
    createdByPersona: "Credit Risk",
  },
  {
    id: uid("cond_10"), applicationId: uid("a08"),
    createdAt: dt(2025, 11, 20), updatedAt: dt(2026, 3, 18),
    conditionType: "Title",
    description: "Title search must confirm no recorded liens, encumbrances, or adverse matters on the property.",
    status: "Satisfied",
    appliesTo: "Property",
    phaseAddedAt: "Application Start",
    createdByPersona: "Closing Team",
  },
  {
    id: uid("cond_11"), applicationId: uid("a08"),
    createdAt: dt(2026, 2, 5), updatedAt: dt(2026, 3, 18),
    conditionType: "Financial Reserve",
    description: "Borrower reserves of 3 months PITIA to be funded and escrowed at closing.",
    status: "Pending",
    appliesTo: "Borrower",
    phaseAddedAt: "Final Credit Review",
    createdByPersona: "Credit Risk",
  },

  // a09 — Docs Back, Retail Chicago
  {
    id: uid("cond_12"), applicationId: uid("a09"),
    createdAt: dt(2026, 1, 15), updatedAt: dt(2026, 3, 14),
    conditionType: "Lease Documentation",
    description: "Borrower to provide current rent roll executed by all tenants prior to docs being drawn.",
    status: "Satisfied",
    appliesTo: "Property",
    phaseAddedAt: "Final Credit Review",
    createdByPersona: "Credit Risk",
  },
  {
    id: uid("cond_13"), applicationId: uid("a09"),
    createdAt: dt(2026, 1, 15), updatedAt: dt(2026, 3, 14),
    conditionType: "Insurance",
    description: "Insurance policy must name lender as additional insured and sole loss payee on all commercial lines.",
    status: "Satisfied",
    appliesTo: "Application",
    phaseAddedAt: "Final Credit Review",
    createdByPersona: "Processing",
  },

  // a10 — Closing, Office San Francisco
  {
    id: uid("cond_14"), applicationId: uid("a10"),
    createdAt: dt(2026, 1, 8), updatedAt: dt(2026, 3, 17),
    conditionType: "Certification",
    description: "Borrower to certify no material change in tenant's financial condition or credit standing since underwriting.",
    status: "Satisfied",
    appliesTo: "Borrower",
    phaseAddedAt: "Final Credit Review",
    createdByPersona: "Credit Risk",
  },
  {
    id: uid("cond_15"), applicationId: uid("a10"),
    createdAt: dt(2026, 1, 8), updatedAt: dt(2026, 3, 17),
    conditionType: "Title",
    description: "Lender's counsel to confirm no adverse title matters and issue title insurance commitment.",
    status: "Satisfied",
    appliesTo: "Property",
    phaseAddedAt: "Final Credit Review",
    createdByPersona: "Closing Team",
  },
];

// ─── Exceptions (3NF) ─────────────────────────────────────────────────────────
// Sourced from what was formerly the creditRiskExceptions string field.
// W1 = lowest authority required; W30 = highest (board-level).

export const SEED_EXCEPTIONS: Exception[] = [
  // a05 — Final Credit Review, Mixed Use Chicago
  {
    id: uid("exc_01"), applicationId: uid("a05"),
    createdAt: dt(2026, 3, 19), updatedAt: dt(2026, 3, 19),
    exceptionType: "Rate Structure",
    description: "Floating rate (SOFR + 175bps) requested in lieu of fixed rate. Justified by value-add business plan with expected refinance within 36 months at stabilization.",
    status: "Approved",
    approvalAuthorityLevel: "W15",
    phaseAddedAt: "Final Credit Review",
    createdByPersona: "Credit Risk",
    approvedBy: "Priya Nair (CRO)",
    approvedAt: dt(2026, 3, 19),
  },

  // a06 — Pre-close, Office Austin
  {
    id: uid("exc_02"), applicationId: uid("a06"),
    createdAt: dt(2026, 1, 10), updatedAt: dt(2026, 3, 10),
    exceptionType: "Concentration Risk",
    description: "Single-tenant concentration exception for NNN office asset. Mitigated by creditworthy tech tenant covenant and borrower net worth of $31M providing strong recourse support.",
    status: "Approved",
    approvalAuthorityLevel: "W12",
    phaseAddedAt: "Application Processing",
    createdByPersona: "Credit Risk",
    approvedBy: "Alan Morse (Credit Risk Officer)",
    approvedAt: dt(2026, 3, 10),
  },

  // a07 — Ready for Docs, Hotel Miami
  {
    id: uid("exc_03"), applicationId: uid("a07"),
    createdAt: dt(2026, 2, 15), updatedAt: dt(2026, 2, 22),
    exceptionType: "Asset Class",
    description: "Hotel/hospitality asset class exception. Policy restricts hospitality to <10% of portfolio. Exception supported by strong post-renovation ADR ($285), RevPAR ($215), and trailing 12-month NOI.",
    status: "Approved",
    approvalAuthorityLevel: "W20",
    phaseAddedAt: "Final Credit Review",
    createdByPersona: "Credit Risk",
    approvedBy: "Credit Committee (2/22/2026)",
    approvedAt: dt(2026, 2, 22),
  },
  {
    id: uid("exc_04"), applicationId: uid("a07"),
    createdAt: dt(2026, 2, 15), updatedAt: dt(2026, 2, 28),
    exceptionType: "IO Structure",
    description: "Interest-only structure for hospitality asset. Policy requires amortization on hotel loans. IO approved for full 5-year term given strong DSCR of 1.32x on IO basis.",
    status: "Approved",
    approvalAuthorityLevel: "W12",
    phaseAddedAt: "Final Credit Review",
    createdByPersona: "Credit Risk",
    approvedBy: "Alan Morse (Credit Risk Officer)",
    approvedAt: dt(2026, 2, 28),
  },

  // a09 — Docs Back, Retail Chicago
  {
    id: uid("exc_05"), applicationId: uid("a09"),
    createdAt: dt(2026, 1, 15), updatedAt: dt(2026, 1, 20),
    exceptionType: "IO Structure",
    description: "Interest-only structure for retail asset. IO approved for 7-year term given all-national-credit tenant roster, 100% occupancy, and DSCR of 1.55x on IO basis.",
    status: "Approved",
    approvalAuthorityLevel: "W8",
    phaseAddedAt: "Final Credit Review",
    createdByPersona: "Credit Risk",
    approvedBy: "Alan Morse (Credit Risk Officer)",
    approvedAt: dt(2026, 1, 20),
  },
];

// ─── Rent Roll (MISMO RentRollItemType) ───────────────────────────────────────
// Seed units for: p04 (MF LA), p08 (MF Atlanta), p05 (Mixed Use Chicago), p02 (Retail NY)

export const SEED_RENT_ROLL: RentRollUnit[] = [
  // ── p04 Multifamily — 2800 Wilshire, Los Angeles (120 units) ──────────────
  {
    id: uid("rr_p04_01"), propertyId: uid("p04"), createdAt: dt(2026, 1, 1), updatedAt: dt(2026, 1, 1),
    unitIdentifier: "101", unitType: "Studio", bedroomCount: "0", bathroomCount: "1",
    squareFeet: "550", tenantName: "Rodriguez, M.", leaseStatus: "Occupied",
    leaseBeginDate: dateStr(2025, 6, 1), leaseEndDate: dateStr(2026, 5, 31),
    monthlyRentAmount: "2,150", marketRentAmount: "2,200",
    annualBaseRentAmount: "", baseRentPsf: "", leaseType: "", renewalOptions: "", tenantIndustry: "",
  },
  {
    id: uid("rr_p04_02"), propertyId: uid("p04"), createdAt: dt(2026, 1, 1), updatedAt: dt(2026, 1, 1),
    unitIdentifier: "102", unitType: "1BR/1BA", bedroomCount: "1", bathroomCount: "1",
    squareFeet: "720", tenantName: "Park, J.", leaseStatus: "Occupied",
    leaseBeginDate: dateStr(2025, 3, 1), leaseEndDate: dateStr(2026, 2, 28),
    monthlyRentAmount: "2,850", marketRentAmount: "2,950",
    annualBaseRentAmount: "", baseRentPsf: "", leaseType: "", renewalOptions: "", tenantIndustry: "",
  },
  {
    id: uid("rr_p04_03"), propertyId: uid("p04"), createdAt: dt(2026, 1, 1), updatedAt: dt(2026, 1, 1),
    unitIdentifier: "201", unitType: "1BR/1BA", bedroomCount: "1", bathroomCount: "1",
    squareFeet: "720", tenantName: "", leaseStatus: "Vacant",
    leaseBeginDate: "", leaseEndDate: "",
    monthlyRentAmount: "", marketRentAmount: "2,950",
    annualBaseRentAmount: "", baseRentPsf: "", leaseType: "", renewalOptions: "", tenantIndustry: "",
  },
  {
    id: uid("rr_p04_04"), propertyId: uid("p04"), createdAt: dt(2026, 1, 1), updatedAt: dt(2026, 1, 1),
    unitIdentifier: "205", unitType: "2BR/2BA", bedroomCount: "2", bathroomCount: "2",
    squareFeet: "1,050", tenantName: "Williams, T. & S.", leaseStatus: "Occupied",
    leaseBeginDate: dateStr(2024, 9, 1), leaseEndDate: dateStr(2026, 8, 31),
    monthlyRentAmount: "3,850", marketRentAmount: "4,000",
    annualBaseRentAmount: "", baseRentPsf: "", leaseType: "", renewalOptions: "", tenantIndustry: "",
  },
  {
    id: uid("rr_p04_05"), propertyId: uid("p04"), createdAt: dt(2026, 1, 1), updatedAt: dt(2026, 1, 1),
    unitIdentifier: "310", unitType: "2BR/2BA+Den", bedroomCount: "2", bathroomCount: "2",
    squareFeet: "1,220", tenantName: "Kim, A.", leaseStatus: "Occupied",
    leaseBeginDate: dateStr(2025, 1, 1), leaseEndDate: dateStr(2026, 12, 31),
    monthlyRentAmount: "4,400", marketRentAmount: "4,500",
    annualBaseRentAmount: "", baseRentPsf: "", leaseType: "", renewalOptions: "", tenantIndustry: "",
  },
  {
    id: uid("rr_p04_06"), propertyId: uid("p04"), createdAt: dt(2026, 1, 1), updatedAt: dt(2026, 1, 1),
    unitIdentifier: "401", unitType: "3BR/2BA", bedroomCount: "3", bathroomCount: "2",
    squareFeet: "1,480", tenantName: "Johnson, R.", leaseStatus: "Notice",
    leaseBeginDate: dateStr(2024, 4, 1), leaseEndDate: dateStr(2026, 3, 31),
    monthlyRentAmount: "5,200", marketRentAmount: "5,500",
    annualBaseRentAmount: "", baseRentPsf: "", leaseType: "", renewalOptions: "", tenantIndustry: "",
  },

  // ── p08 Multifamily — 3200 Peachtree Rd, Atlanta (224 units) ─────────────
  {
    id: uid("rr_p08_01"), propertyId: uid("p08"), createdAt: dt(2026, 1, 1), updatedAt: dt(2026, 1, 1),
    unitIdentifier: "1A", unitType: "Studio", bedroomCount: "0", bathroomCount: "1",
    squareFeet: "490", tenantName: "Patel, S.", leaseStatus: "Occupied",
    leaseBeginDate: dateStr(2025, 8, 1), leaseEndDate: dateStr(2026, 7, 31),
    monthlyRentAmount: "1,750", marketRentAmount: "1,800",
    annualBaseRentAmount: "", baseRentPsf: "", leaseType: "", renewalOptions: "", tenantIndustry: "",
  },
  {
    id: uid("rr_p08_02"), propertyId: uid("p08"), createdAt: dt(2026, 1, 1), updatedAt: dt(2026, 1, 1),
    unitIdentifier: "2B", unitType: "1BR/1BA", bedroomCount: "1", bathroomCount: "1",
    squareFeet: "680", tenantName: "Thompson, C.", leaseStatus: "Occupied",
    leaseBeginDate: dateStr(2025, 2, 1), leaseEndDate: dateStr(2026, 1, 31),
    monthlyRentAmount: "2,200", marketRentAmount: "2,300",
    annualBaseRentAmount: "", baseRentPsf: "", leaseType: "", renewalOptions: "", tenantIndustry: "",
  },
  {
    id: uid("rr_p08_03"), propertyId: uid("p08"), createdAt: dt(2026, 1, 1), updatedAt: dt(2026, 1, 1),
    unitIdentifier: "4C", unitType: "2BR/2BA", bedroomCount: "2", bathroomCount: "2",
    squareFeet: "980", tenantName: "Garcia, M. & L.", leaseStatus: "Occupied",
    leaseBeginDate: dateStr(2024, 11, 1), leaseEndDate: dateStr(2026, 10, 31),
    monthlyRentAmount: "3,100", marketRentAmount: "3,250",
    annualBaseRentAmount: "", baseRentPsf: "", leaseType: "", renewalOptions: "", tenantIndustry: "",
  },
  {
    id: uid("rr_p08_04"), propertyId: uid("p08"), createdAt: dt(2026, 1, 1), updatedAt: dt(2026, 1, 1),
    unitIdentifier: "5D", unitType: "2BR/2BA", bedroomCount: "2", bathroomCount: "2",
    squareFeet: "980", tenantName: "Lee, H.", leaseStatus: "Occupied",
    leaseBeginDate: dateStr(2025, 5, 1), leaseEndDate: dateStr(2026, 4, 30),
    monthlyRentAmount: "3,200", marketRentAmount: "3,250",
    annualBaseRentAmount: "", baseRentPsf: "", leaseType: "", renewalOptions: "", tenantIndustry: "",
  },
  {
    id: uid("rr_p08_05"), propertyId: uid("p08"), createdAt: dt(2026, 1, 1), updatedAt: dt(2026, 1, 1),
    unitIdentifier: "7A", unitType: "3BR/2BA", bedroomCount: "3", bathroomCount: "2",
    squareFeet: "1,380", tenantName: "Brown, K.", leaseStatus: "Occupied",
    leaseBeginDate: dateStr(2025, 7, 1), leaseEndDate: dateStr(2027, 6, 30),
    monthlyRentAmount: "4,100", marketRentAmount: "4,300",
    annualBaseRentAmount: "", baseRentPsf: "", leaseType: "", renewalOptions: "", tenantIndustry: "",
  },
  {
    id: uid("rr_p08_06"), propertyId: uid("p08"), createdAt: dt(2026, 1, 1), updatedAt: dt(2026, 1, 1),
    unitIdentifier: "8B", unitType: "1BR/1BA", bedroomCount: "1", bathroomCount: "1",
    squareFeet: "680", tenantName: "", leaseStatus: "Vacant",
    leaseBeginDate: "", leaseEndDate: "",
    monthlyRentAmount: "", marketRentAmount: "2,300",
    annualBaseRentAmount: "", baseRentPsf: "", leaseType: "", renewalOptions: "", tenantIndustry: "",
  },

  // ── p05 Mixed Use — 330 N Michigan Ave, Chicago (48 units) ───────────────
  {
    id: uid("rr_p05_01"), propertyId: uid("p05"), createdAt: dt(2026, 1, 1), updatedAt: dt(2026, 1, 1),
    unitIdentifier: "2A", unitType: "1BR/1BA", bedroomCount: "1", bathroomCount: "1",
    squareFeet: "750", tenantName: "Walsh, D.", leaseStatus: "Occupied",
    leaseBeginDate: dateStr(2025, 4, 1), leaseEndDate: dateStr(2026, 3, 31),
    monthlyRentAmount: "2,600", marketRentAmount: "2,700",
    annualBaseRentAmount: "", baseRentPsf: "", leaseType: "", renewalOptions: "", tenantIndustry: "",
  },
  {
    id: uid("rr_p05_02"), propertyId: uid("p05"), createdAt: dt(2026, 1, 1), updatedAt: dt(2026, 1, 1),
    unitIdentifier: "3B", unitType: "2BR/2BA", bedroomCount: "2", bathroomCount: "2",
    squareFeet: "1,100", tenantName: "Chen, W. & Y.", leaseStatus: "Occupied",
    leaseBeginDate: dateStr(2024, 10, 1), leaseEndDate: dateStr(2026, 9, 30),
    monthlyRentAmount: "3,700", marketRentAmount: "3,850",
    annualBaseRentAmount: "", baseRentPsf: "", leaseType: "", renewalOptions: "", tenantIndustry: "",
  },
  {
    id: uid("rr_p05_03"), propertyId: uid("p05"), createdAt: dt(2026, 1, 1), updatedAt: dt(2026, 1, 1),
    unitIdentifier: "Suite 101", unitType: "Retail", bedroomCount: "0", bathroomCount: "0",
    squareFeet: "4,200", tenantName: "Lakeside Coffee Co.", leaseStatus: "Occupied",
    leaseBeginDate: dateStr(2023, 1, 1), leaseEndDate: dateStr(2028, 12, 31),
    monthlyRentAmount: "", marketRentAmount: "",
    annualBaseRentAmount: "210,000", baseRentPsf: "50.00",
    leaseType: "NNN", renewalOptions: "Two 5-year options at 3% annual escalation",
    tenantIndustry: "Food & Beverage",
  },
  {
    id: uid("rr_p05_04"), propertyId: uid("p05"), createdAt: dt(2026, 1, 1), updatedAt: dt(2026, 1, 1),
    unitIdentifier: "Suite 102", unitType: "Office", bedroomCount: "0", bathroomCount: "0",
    squareFeet: "2,800", tenantName: "Midwest Financial Group", leaseStatus: "Occupied",
    leaseBeginDate: dateStr(2022, 6, 1), leaseEndDate: dateStr(2027, 5, 31),
    monthlyRentAmount: "", marketRentAmount: "",
    annualBaseRentAmount: "168,000", baseRentPsf: "60.00",
    leaseType: "Modified Gross", renewalOptions: "One 3-year option",
    tenantIndustry: "Financial Services",
  },

  // ── p02 Retail — 850 Fifth Ave, New York (12 units) ──────────────────────
  {
    id: uid("rr_p02_01"), propertyId: uid("p02"), createdAt: dt(2026, 1, 1), updatedAt: dt(2026, 1, 1),
    unitIdentifier: "G-01", unitType: "Retail", bedroomCount: "0", bathroomCount: "0",
    squareFeet: "8,500", tenantName: "National Pharmacy Partners", leaseStatus: "Occupied",
    leaseBeginDate: dateStr(2017, 3, 1), leaseEndDate: dateStr(2035, 2, 28),
    monthlyRentAmount: "", marketRentAmount: "",
    annualBaseRentAmount: "1,275,000", baseRentPsf: "150.00",
    leaseType: "NNN", renewalOptions: "Four 5-year options at fixed rent",
    tenantIndustry: "Pharmacy / Healthcare Retail",
  },
  {
    id: uid("rr_p02_02"), propertyId: uid("p02"), createdAt: dt(2026, 1, 1), updatedAt: dt(2026, 1, 1),
    unitIdentifier: "G-02", unitType: "Retail", bedroomCount: "0", bathroomCount: "0",
    squareFeet: "4,200", tenantName: "Luxe Apparel NYC", leaseStatus: "Occupied",
    leaseBeginDate: dateStr(2021, 9, 1), leaseEndDate: dateStr(2028, 8, 31),
    monthlyRentAmount: "", marketRentAmount: "",
    annualBaseRentAmount: "756,000", baseRentPsf: "180.00",
    leaseType: "NNN", renewalOptions: "One 5-year option",
    tenantIndustry: "Luxury Retail",
  },
  {
    id: uid("rr_p02_03"), propertyId: uid("p02"), createdAt: dt(2026, 1, 1), updatedAt: dt(2026, 1, 1),
    unitIdentifier: "G-03", unitType: "Retail", bedroomCount: "0", bathroomCount: "0",
    squareFeet: "3,100", tenantName: "", leaseStatus: "Vacant",
    leaseBeginDate: "", leaseEndDate: "",
    monthlyRentAmount: "", marketRentAmount: "",
    annualBaseRentAmount: "", baseRentPsf: "175.00",
    leaseType: "NNN", renewalOptions: "", tenantIndustry: "",
  },
];

// ─── Operating History (MISMO IncomeExpenseStatementType) ─────────────────────
// Seed periods for: p04 (MF LA), p08 (MF Atlanta), p03 (Industrial ATL), p02 (Retail NY)

export const SEED_OPERATING_HISTORY: OperatingYear[] = [
  // ── p04 Multifamily LA — 120 units ───────────────────────────────────────
  {
    id: uid("oh_p04_1"), propertyId: uid("p04"), createdAt: dt(2026, 1, 1), updatedAt: dt(2026, 1, 1),
    periodType: "Actual Year 1", periodYear: "2023",
    grossPotentialRent: "3,888,000", vacancyAndCreditLoss: "311,040", otherIncome: "72,000",
    effectiveGrossIncome: "3,648,960",
    realEstateTaxes: "268,000", insurance: "88,000", utilities: "172,000",
    repairsAndMaintenance: "228,000", managementFee: "182,448", administrative: "80,000",
    replacementReserves: "36,000", otherExpenses: "38,000", totalOperatingExpenses: "1,092,448",
    netOperatingIncome: "2,556,512",
  },
  {
    id: uid("oh_p04_2"), propertyId: uid("p04"), createdAt: dt(2026, 1, 1), updatedAt: dt(2026, 1, 1),
    periodType: "Actual Year 2", periodYear: "2024",
    grossPotentialRent: "4,032,000", vacancyAndCreditLoss: "282,240", otherIncome: "80,000",
    effectiveGrossIncome: "3,829,760",
    realEstateTaxes: "278,000", insurance: "92,000", utilities: "176,000",
    repairsAndMaintenance: "236,000", managementFee: "191,488", administrative: "83,000",
    replacementReserves: "36,000", otherExpenses: "40,000", totalOperatingExpenses: "1,132,488",
    netOperatingIncome: "2,697,272",
  },
  {
    id: uid("oh_p04_3"), propertyId: uid("p04"), createdAt: dt(2026, 1, 1), updatedAt: dt(2026, 1, 1),
    periodType: "T12 (Trailing 12)", periodYear: "2025",
    grossPotentialRent: "4,176,000", vacancyAndCreditLoss: "292,320", otherIncome: "85,000",
    effectiveGrossIncome: "3,968,680",
    realEstateTaxes: "285,000", insurance: "95,000", utilities: "180,000",
    repairsAndMaintenance: "242,000", managementFee: "198,434", administrative: "86,000",
    replacementReserves: "36,000", otherExpenses: "42,000", totalOperatingExpenses: "1,164,434",
    netOperatingIncome: "2,804,246",
  },

  // ── p08 Multifamily Atlanta — 224 units ──────────────────────────────────
  {
    id: uid("oh_p08_1"), propertyId: uid("p08"), createdAt: dt(2026, 1, 1), updatedAt: dt(2026, 1, 1),
    periodType: "Actual Year 1", periodYear: "2024",
    grossPotentialRent: "7,526,400", vacancyAndCreditLoss: "376,320", otherIncome: "145,000",
    effectiveGrossIncome: "7,295,080",
    realEstateTaxes: "510,000", insurance: "196,000", utilities: "324,000",
    repairsAndMaintenance: "448,000", managementFee: "364,754", administrative: "158,000",
    replacementReserves: "67,200", otherExpenses: "72,000", totalOperatingExpenses: "2,139,954",
    netOperatingIncome: "5,155,126",
  },
  {
    id: uid("oh_p08_2"), propertyId: uid("p08"), createdAt: dt(2026, 1, 1), updatedAt: dt(2026, 1, 1),
    periodType: "T12 (Trailing 12)", periodYear: "2025",
    grossPotentialRent: "7,795,200", vacancyAndCreditLoss: "233,856", otherIncome: "158,000",
    effectiveGrossIncome: "7,719,344",
    realEstateTaxes: "525,000", insurance: "204,000", utilities: "332,000",
    repairsAndMaintenance: "462,000", managementFee: "385,967", administrative: "164,000",
    replacementReserves: "67,200", otherExpenses: "76,000", totalOperatingExpenses: "2,216,167",
    netOperatingIncome: "5,503,177",
  },

  // ── p03 Industrial Atlanta — 312,000 sqft ─────────────────────────────────
  {
    id: uid("oh_p03_1"), propertyId: uid("p03"), createdAt: dt(2026, 1, 1), updatedAt: dt(2026, 1, 1),
    periodType: "T12 (Trailing 12)", periodYear: "2025",
    grossPotentialRent: "4,368,000", vacancyAndCreditLoss: "218,400", otherIncome: "24,000",
    effectiveGrossIncome: "4,173,600",
    realEstateTaxes: "312,000", insurance: "145,000", utilities: "48,000",
    repairsAndMaintenance: "186,000", managementFee: "208,680", administrative: "72,000",
    replacementReserves: "62,400", otherExpenses: "28,000", totalOperatingExpenses: "1,062,080",
    netOperatingIncome: "3,111,520",
  },

  // ── p02 Retail NY — 36,500 sqft ───────────────────────────────────────────
  {
    id: uid("oh_p02_1"), propertyId: uid("p02"), createdAt: dt(2026, 1, 1), updatedAt: dt(2026, 1, 1),
    periodType: "T12 (Trailing 12)", periodYear: "2025",
    grossPotentialRent: "2,356,200", vacancyAndCreditLoss: "235,620", otherIncome: "18,000",
    effectiveGrossIncome: "2,138,580",
    realEstateTaxes: "188,000", insurance: "72,000", utilities: "0",
    repairsAndMaintenance: "62,000", managementFee: "106,929", administrative: "38,000",
    replacementReserves: "18,250", otherExpenses: "22,000", totalOperatingExpenses: "507,179",
    netOperatingIncome: "1,631,401",
  },
];
